"""original_radio lane -- registry, dispatch, creative front, QA, provenance.

CHUNK B tests (ARCHITECTURE_V4 + R2_CODING_PLAN + R3 deltas + r4 pins,
2026-07-09). Pure Python; no GPU, no real LLM, no network: every LLM call
is a canned-JSON fake through the real structured_call ladder.
"""
from __future__ import annotations

import dataclasses
import json
import sys
from pathlib import Path
from types import SimpleNamespace

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from nodes import _otr_original_radio as ORR  # noqa: E402
from nodes import _otr_source_payload as OSP  # noqa: E402
from nodes import _otr_story_routing as ROUTING  # noqa: E402
from nodes import OTR_LedgerScriptWriter as W  # noqa: E402
from nodes._otr_structured_call import StructuredCallFailedError  # noqa: E402


@pytest.fixture(autouse=True)
def _fresh_registry():
    ROUTING._REGISTRY = None
    yield
    ROUTING._REGISTRY = None


# ---------------------------------------------------------------------------
# 1. Registry: rows + sweep (runnable-on-build set is live)
# ---------------------------------------------------------------------------

class TestRegistry:
    def test_real_registry_loads_with_original_row(self):
        ids = ROUTING.list_bank_ids()
        assert "original_radio" in ids
        assert ids[-1] == "custom_source_bank"  # "+ Add Your Own" stays last

    def test_bank_row_shape(self):
        bank = ROUTING.get_bank("original_radio")
        assert bank.runnable is True
        assert bank.fetcher == "" and bank.interpreter == ""
        assert bank.default_story_pipeline == "original_multi_pass"
        d = bank.defaults
        assert d.get("hud_origin_label") == "STORY ORIGIN"
        assert "generated by machine" in d.get("credits_source_line", "")
        assert "coda_mode" not in d  # V4 lock 8: dead config class

    def test_science_has_no_new_defaults(self):
        # Byte-identity guard: legacy banks must NOT grow the new keys.
        d = ROUTING.get_bank("science_news").defaults
        assert "hud_origin_label" not in d
        assert "credits_source_line" not in d

    def test_pipeline_row_shape(self):
        pipe = ROUTING.get_pipeline("original_multi_pass")
        assert pipe.executable is True          # sweep 4b elif demands it
        assert pipe.requires_source_contract is False
        assert pipe.declared_seams == frozenset({
            "original_concept_system", "original_select_system",
            "original_brief_system", "original_qa_system",
        })

    def test_pack_carries_13_stages_and_required_subset(self):
        bank = ROUTING.get_bank("original_radio")
        pack = ROUTING.resolve_story_pack("original_radio")
        assert len(pack.prompt_stages) == 13
        assert set(bank.required_seams) <= set(pack.prompt_stages)
        for seam in ("original_concept_system", "original_select_system",
                     "original_brief_system", "original_qa_system"):
            assert pack.prompt_stages[seam].strip()

    def test_sweep_demands_executable_true(self):
        # The r2 M2 pin, both directions: the REAL set passes (loaded
        # above); a fixture with executable:false raises the 4b elif.
        reg = ROUTING._ensure_loaded()
        bad_pipe = dataclasses.replace(
            reg.pipelines["original_multi_pass"], executable=False)
        pipelines = dict(reg.pipelines)
        pipelines["original_multi_pass"] = bad_pipe
        # Full real bank map: the sweep also audits the packs DIRECTORY
        # against the bank ids, so a single-bank fixture dies earlier.
        with pytest.raises(ROUTING.RegistryValidationError,
                           match="runner to exist"):
            ROUTING._sweep_and_crossref(dict(reg.banks), pipelines)

    def test_custom_bank_still_dies_at_run_gate(self):
        with pytest.raises(ROUTING.StoryBankNotRunnableError):
            ROUTING.require_runnable_bank("custom_source_bank")

    def test_story_rules_resolve_for_original(self):
        rules = __import__(
            "nodes._otr_story_rules", fromlist=["resolve_story_rules"]
        ).resolve_story_rules("original_radio")
        assert rules is not None


# ---------------------------------------------------------------------------
# 2. Dispatch helper (r4 P8)
# ---------------------------------------------------------------------------

class TestDispatch:
    def test_bank_shape_test(self):
        assert W._bank_has_no_source_contract(
            ROUTING.get_bank("original_radio")) is True
        assert W._bank_has_no_source_contract(
            ROUTING.get_bank("science_news")) is False
        # custom is empty-empty but runnable:false -> NOT the original
        # lane: a direct _resolve_inputs call keeps its pinned LOUD
        # SourceContractMissingError path (chunk3 test).
        assert W._bank_has_no_source_contract(
            ROUTING.get_bank("custom_source_bank")) is False


# ---------------------------------------------------------------------------
# 3. A-branch payload (spark digest; operator_hint rides source_meta)
# ---------------------------------------------------------------------------

class TestResolveInputsOriginal:
    def test_payload_contract_and_sidecars(self, monkeypatch):
        monkeypatch.setenv("OTR_ORIGINAL_SEED", "pin-42")
        r = W._resolve_inputs(
            source_bank="original_radio", custom_premise="  a night ferry  ",
        )
        art = r["news_article"]
        assert set(art) == OSP.SOURCE_PAYLOAD_KEYS
        assert art["source"] == "Original (LLM)"
        assert art["seed_text"].strip()
        assert r["seed_source"] == "original_llm"
        sm = r["source_meta"]
        assert sm["kind"] == "original_llm"
        assert set(sm["spark_atoms"]) == set(ORR.DECK_AXES)
        assert sm["operator_hint"] == "a night ferry"   # r4 P2: not payload
        assert "operator_hint" not in art
        assert r["source_rights"]["license_label"] == "synthetic original"

    def test_seeded_draw_is_reproducible(self, monkeypatch):
        monkeypatch.setenv("OTR_ORIGINAL_SEED", "pin-42")
        a = W._resolve_inputs(source_bank="original_radio")
        b = W._resolve_inputs(source_bank="original_radio")
        assert (a["source_meta"]["spark_atoms"]
                == b["source_meta"]["spark_atoms"])

    def test_science_path_unaffected_by_custom(self):
        r = W._resolve_inputs(
            source_bank="science_news", custom_premise="my premise",
        )
        assert r["news_article"]["source"] == "User Seed"
        assert r["source_meta"] == {}


# ---------------------------------------------------------------------------
# 4. Deck + creative front (canned-JSON fakes through the real ladder)
# ---------------------------------------------------------------------------

def _seq_fn(*replies):
    it = iter(replies)
    last = replies[-1]

    def _fn(messages, **kw):
        return next(it, last)
    return _fn


_CONCEPT_JSON = json.dumps({"pitches": [
    {"logline": f"Pitch {i}: a ferrywoman conceals a pawn ticket at the lock",
     "hook": "who redeems it", "radio_device": "a silence where a reply should be",
     "cast_sketch": [{"name": "MARA", "role": "ferrywoman"},
                     {"name": "ELLIS", "role": "lock keeper"}]}
    for i in range(3)
]})
_SELECT_JSON = json.dumps({
    "selected_index": 1,
    "pitch": {"logline": "MARA conceals a pawn ticket from ELLIS at the lock",
              "hook": "the ticket names no item",
              "radio_device": "a silence where a reply should be"},
    "cast": [
        {"name": "MARA", "want": "to keep the ticket", "pressure": "the toll",
         "relationship": "works the lock with ELLIS"},
        {"name": "ELLIS", "want": "an honest ledger", "pressure": "the audit",
         "relationship": "trusts MARA too far"},
    ],
    "selection_rationale": "two voices, one object, audible standoff",
})
_BRIEFS_JSON = json.dumps({
    "casting_brief": ("MARA, a ferrywoman: level voice that shortens when the"
                      " pawn ticket comes near. ELLIS, a lock keeper: dry,"
                      " precise, counts everything twice."),
    "script_brief": ("At the canal lock, MARA conceals a pawn ticket that"
                     " names no item; ELLIS balances a ledger that will not"
                     " close. The episode opens at dusk and ends when the"
                     " ticket is read aloud."),
    "key_terms": ["pawn ticket", "ELLIS"],
})


class TestCreativeFront:
    def test_deck_loads_and_draws(self):
        deck = ORR.load_spark_deck()
        draw = ORR.draw_spark_atoms(deck)
        assert set(draw.atoms) == set(ORR.DECK_AXES)
        assert draw.digest.strip() and draw.deck_version == "v1"

    def test_forbidden_scan(self):
        with pytest.raises(ORR.OriginalRadioError, match="forbidden"):
            ORR.scan_forbidden("he drew a gun", origin="t")

    def _pack(self):
        return ROUTING.resolve_story_pack("original_radio")

    def test_front_green_and_contract(self):
        briefs, delta = ORR.build_original_briefs(
            spark_atoms={"place": "the lock"},
            num_characters=2,
            creative_fn=_seq_fn(_CONCEPT_JSON, _SELECT_JSON),
            technical_fn=_seq_fn(_BRIEFS_JSON),
            creative_model_id="c-model", technical_model_id="t-model",
            pack=self._pack(),
        )
        dump = OSP.validate_interpreter_result(briefs, origin="test")
        assert dump["news_close_brief"] == ""       # V4 lock 1
        assert dump["key_terms"] == ["pawn ticket", "ELLIS"]
        assert delta["selected_concept"]["selected_index"] == 1
        assert len(delta["pitches"]) == 3
        assert delta["model_ids"] == {"creative": "c-model",
                                      "technical": "t-model"}

    def test_wrong_cast_count_exhausts(self):
        bad = json.dumps({"pitches": json.loads(_CONCEPT_JSON)["pitches"]})
        with pytest.raises(StructuredCallFailedError):
            ORR.build_original_briefs(
                spark_atoms={"place": "the lock"},
                num_characters=3,   # pitches carry 2 -> gate rejects x3
                creative_fn=_seq_fn(bad),
                technical_fn=_seq_fn(_BRIEFS_JSON),
                pack=self._pack(),
            )

    def test_ungrounded_key_term_exhausts(self):
        bad_briefs = json.dumps({
            **json.loads(_BRIEFS_JSON),
            "key_terms": ["pawn ticket", "ZEPPELIN"],
        })
        with pytest.raises(StructuredCallFailedError):
            ORR.build_original_briefs(
                spark_atoms={"place": "the lock"},
                num_characters=2,
                creative_fn=_seq_fn(_CONCEPT_JSON, _SELECT_JSON),
                technical_fn=_seq_fn(bad_briefs),
                pack=self._pack(),
            )

    def test_key_term_grounds_across_a_line_wrap(self):
        # A2 normalization (live-smoke hardening 2026-07-09): the corpus
        # joins fields with newlines and a field may wrap a phrase across
        # a line break; a key_term copied verbatim must still ground.
        sel = json.loads(_SELECT_JSON)
        sel["pitch"]["logline"] = (
            "MARA conceals a pawn\nticket from ELLIS at the lock")
        briefs, _ = ORR.build_original_briefs(
            spark_atoms={"place": "the lock"},
            num_characters=2,
            creative_fn=_seq_fn(_CONCEPT_JSON, json.dumps(sel)),
            technical_fn=_seq_fn(_BRIEFS_JSON),
            pack=self._pack(),
        )
        assert briefs.key_terms == ["pawn ticket", "ELLIS"]

    def test_ungrounded_key_term_pruned_deterministically(self):
        # The 2026-07-09 live-smoke failure class: one paraphrased
        # key_term ('grieving mother') exhausted the ladder. With >= 2
        # verbatim terms surviving, the A2 deterministic repair must
        # prune the paraphrase and finish with NO second technical call.
        calls = {"n": 0}
        bad = json.dumps({
            **json.loads(_BRIEFS_JSON),
            "key_terms": ["pawn ticket", "ELLIS", "grieving mother"],
        })

        def tech_fn(messages, **kw):
            calls["n"] += 1
            return bad

        briefs, _ = ORR.build_original_briefs(
            spark_atoms={"place": "the lock"},
            num_characters=2,
            creative_fn=_seq_fn(_CONCEPT_JSON, _SELECT_JSON),
            technical_fn=tech_fn,
            pack=self._pack(),
        )
        assert briefs.key_terms == ["pawn ticket", "ELLIS"]
        assert calls["n"] == 1, "prune must not spend an LLM repair call"

    def test_prune_declines_below_two_grounded_terms(self):
        # Only one grounded term would survive -> the prune declines,
        # the typed A2 LLM repair turn runs (and re-fails on the canned
        # reply), and the ladder exhausts loud.
        calls = {"n": 0}
        bad = json.dumps({
            **json.loads(_BRIEFS_JSON),
            "key_terms": ["pawn ticket", "ZEPPELIN"],
        })

        def tech_fn(messages, **kw):
            calls["n"] += 1
            if calls["n"] > 1:
                # The repair turn must carry the typed A2 directive.
                assert "COPIED verbatim" in json.dumps(messages)
            return bad

        with pytest.raises(StructuredCallFailedError):
            ORR.build_original_briefs(
                spark_atoms={"place": "the lock"},
                num_characters=2,
                creative_fn=_seq_fn(_CONCEPT_JSON, _SELECT_JSON),
                technical_fn=tech_fn,
                pack=self._pack(),
            )
        assert calls["n"] == 2, "base + one typed LLM repair, then loud"

    def test_nonempty_close_brief_rejected(self):
        bad_briefs = json.dumps({
            **json.loads(_BRIEFS_JSON),
            "news_close_brief": "tonight's tale was generated",
        })
        with pytest.raises(StructuredCallFailedError):
            ORR.build_original_briefs(
                spark_atoms={"place": "the lock"},
                num_characters=2,
                creative_fn=_seq_fn(_CONCEPT_JSON, _SELECT_JSON),
                technical_fn=_seq_fn(bad_briefs),
                pack=self._pack(),
            )


# ---------------------------------------------------------------------------
# 5. Interpreter adapter (D.2 shape + D3 restamp)
# ---------------------------------------------------------------------------

class TestInterpreterAdapter:
    def test_adapter_runs_and_restamps_both_surfaces(self):
        resolved = {
            "source_meta": {"kind": "original_llm",
                            "spark_atoms": {"place": "the lock"}},
            "num_characters": 2,
            "creative_writing_model": "c-model",
        }
        meta = {"source_meta": dict(resolved["source_meta"])}
        adapter = W._make_original_interpreter(
            creative_fn=_seq_fn(_CONCEPT_JSON, _SELECT_JSON),
            resolved=resolved, meta=meta,
        )
        bank = ROUTING.get_bank("original_radio")
        briefs = adapter(bank=bank, payload={"ignored": "yes"},
                         technical_fn=_seq_fn(_BRIEFS_JSON),
                         model_id="t-model")
        assert briefs.casting_brief
        # r3 D3: the delta reached BOTH surfaces.
        for surface in (resolved["source_meta"], meta["source_meta"]):
            assert "selected_concept" in surface
            assert surface["model_ids"]["technical"] == "t-model"

    def test_adapter_without_atoms_fails_loud(self):
        adapter = W._make_original_interpreter(
            creative_fn=_seq_fn(_CONCEPT_JSON), resolved={"source_meta": {},
            "num_characters": 2, "creative_writing_model": "c"}, meta={},
        )
        with pytest.raises(ORR.OriginalBriefsError, match="spark_atoms"):
            adapter(bank=ROUTING.get_bank("original_radio"), payload={},
                    technical_fn=_seq_fn(_BRIEFS_JSON), model_id="t")


# ---------------------------------------------------------------------------
# 6. QA gate (clean / fail-class / coalesced repair, r4 P3+P4)
# ---------------------------------------------------------------------------

def _qa_ledger():
    return SimpleNamespace(
        data={
            "lines": [
                {"line_id": "a0", "speaker_role": "announcer",
                 "text": "Good evening.", "compose_flags": ["announcer_intro"]},
                {"line_id": "b1", "speaker_role": "character",
                 "text": "MARA: The ticket names no item.", "char_id": "mara"},
                {"line_id": "z9", "speaker_role": "announcer",
                 "text": "This has been SIGNAL LOST.",
                 "compose_flags": ["announcer_outro", "news_coda_no_brief"]},
            ],
            "cast": [{"name": "Mara"}],
        },
        save=lambda self=None: None,
    )


def _findings_fn(*payloads):
    return _seq_fn(*[json.dumps({"findings": p}) for p in payloads])


class TestQAGate:
    def _run(self, led, technical_fn, monkeypatch, compose_text=None):
        if compose_text is not None:
            import nodes._otr_line_composer as LC

            def _fake_outro(**kw):
                return LC.LineResult(text=compose_text,
                                     compose_flags=("announcer_outro",))
            monkeypatch.setattr(LC, "compose_announcer_outro", _fake_outro)
        resolved = {"technical_model": "t", "creative_writing_model": "c",
                    "source_bank": "original_radio"}
        meta = {"source_meta": {"concept_corpus": "the lock"},
                "dramatic_state": {"ending_change": "the ticket is read"}}
        W._run_original_qa_gate(
            led, meta, resolved,
            bank_row=ROUTING.get_bank("original_radio"),
            technical_fn=technical_fn,
            creative_fn=lambda *a, **k: "",
            first_announcer_id="a0", last_announcer_id="z9",
            script_brief="brief", nc_brief="",
        )
        return meta

    def test_clean(self, monkeypatch):
        meta = self._run(_qa_ledger(), _findings_fn([]), monkeypatch)
        assert meta["original_qa"] == {"status": "clean", "repaired": False}

    def test_fail_class_raises(self, monkeypatch):
        fn = _findings_fn([{"class": "weapons_smoking",
                            "detail": "MARA mentions a pistol"}])
        with pytest.raises(ORR.OriginalQAError, match="weapons_smoking"):
            self._run(_qa_ledger(), fn, monkeypatch)

    def test_epilogue_repair_preserves_flags(self, monkeypatch):
        led = _qa_ledger()
        fn = _findings_fn(
            [{"class": "epilogue_moralizes", "detail": "the lesson is"}],
            [],   # re-judge: clean
        )
        meta = self._run(led, fn, monkeypatch,
                         compose_text="A wry new closing line.")
        assert meta["original_qa"] == {"status": "clean", "repaired": True}
        row = led.data["lines"][2]
        assert row["text"] == "A wry new closing line."
        assert "news_coda_no_brief" in row["compose_flags"]       # r4 P3
        assert "original_qa_outro_recomposed" in row["compose_flags"]

    def test_still_dirty_after_repair_raises(self, monkeypatch):
        fn = _findings_fn(
            [{"class": "epilogue_moralizes", "detail": "the lesson is"}],
            [{"class": "epilogue_moralizes", "detail": "still moralizing"}],
        )
        with pytest.raises(ORR.OriginalQAError, match="still dirty"):
            self._run(_qa_ledger(), fn, monkeypatch,
                      compose_text="Another closing line.")

    def test_epilogue_missing_refuted_when_outro_exists(self, monkeypatch):
        # Run-5 live catch (2026-07-10): the re-judge re-claimed
        # 'epilogue_missing' about the recomposed non-empty outro row
        # it had just been shown. Python refutes the absence claim
        # deterministically; the episode survives, discard stamped.
        led = _qa_ledger()
        fn = _findings_fn(
            [{"class": "epilogue_missing", "detail": "no closing line"}],
            [{"class": "epilogue_missing",
              "detail": "still no closing line"}],
        )
        meta = self._run(led, fn, monkeypatch,
                         compose_text="A wry recomposed closing line.")
        assert meta["original_qa"]["status"] == "clean_after_discard"
        assert meta["original_qa"]["repaired"] is True
        assert meta["original_qa"]["discarded"] == ["epilogue_missing"]

    def test_hallucinated_hard_findings_discarded_then_clean(self, monkeypatch):
        # The 2026-07-09 live-smoke trio: weapons on a weaponless
        # threat, news framing on a teaser, epilogue_missing with the
        # outro present. Evidence bar: confirm drops the hard pair;
        # the epilogue class takes the ONE bounded repair; re-judge
        # clean -> episode survives, discards stamped for audit.
        led = _qa_ledger()
        fn = _seq_fn(
            json.dumps({"findings": [
                {"class": "weapons_smoking",
                 "detail": "the sirens will be the last thing you hear"},
                {"class": "news_source_framing",
                 "detail": "Late tonight in a dim office"},
                {"class": "epilogue_missing",
                 "detail": "The closing line does not comment"},
            ]}),
            json.dumps({"confirmed": []}),   # confirm pass drops both
            json.dumps({"findings": []}),    # re-judge after repair
        )
        meta = self._run(led, fn, monkeypatch,
                         compose_text="A dry closing line.")
        assert meta["original_qa"]["status"] == "clean_after_discard"
        assert meta["original_qa"]["repaired"] is True
        assert sorted(meta["original_qa"]["discarded"]) == [
            "news_source_framing", "weapons_smoking"]

    def test_all_hard_discarded_no_epilogue_continues(self, monkeypatch):
        fn = _seq_fn(
            json.dumps({"findings": [
                {"class": "weapons_smoking",
                 "detail": "the sirens sound ominous"},
            ]}),
            json.dumps({"confirmed": []}),
        )
        meta = self._run(_qa_ledger(), fn, monkeypatch)
        assert meta["original_qa"]["status"] == "clean_after_discard"
        assert meta["original_qa"]["discarded"] == ["weapons_smoking"]

    def test_confirmed_hard_finding_still_kills(self, monkeypatch):
        # The confirm pass produces a verbatim script quote -> the
        # kill goes through with the evidence recorded.
        fn = _seq_fn(
            json.dumps({"findings": [
                {"class": "news_source_framing",
                 "detail": "the intro frames the tale"},
            ]}),
            json.dumps({"confirmed": [
                {"class": "news_source_framing",
                 "quote": "This has been SIGNAL LOST."},
            ]}),
        )
        with pytest.raises(ORR.OriginalQAError, match="confirmed quote"):
            self._run(_qa_ledger(), fn, monkeypatch)


# ---------------------------------------------------------------------------
# 6b. Hard-finding evidence triage (pure module, live-smoke hardening)
# ---------------------------------------------------------------------------

class TestHardFindingTriage:
    _SCRIPT = ("ANNOUNCER: Good evening.\n"
               "MARA: I am reaching for the lever by the door.\n"
               "ANNOUNCER: This has been SIGNAL LOST.")

    def _finding(self, cls, detail):
        return ORR.QAFinding.model_validate({"class": cls, "detail": detail})

    def test_lexicon_corroboration_kills_without_llm(self):
        calls = {"n": 0}

        def tech_fn(messages, **kw):
            calls["n"] += 1
            return "{}"

        kills, discarded = ORR.triage_hard_findings(
            [self._finding("weapons_smoking", "MARA draws a pistol")],
            script=self._SCRIPT, technical_fn=tech_fn)
        assert len(kills) == 1 and not discarded
        assert "pistol" in kills[0][1]
        assert calls["n"] == 0, "lexicon kill must not spend an LLM call"

    def test_lexicon_only_class_discards_without_confirm(self):
        # Run-3 live catch (2026-07-10): 'coils start to smoke' is not
        # tobacco; a lexicon_only class with no lexicon hit is judge
        # noise and must be discarded with ZERO LLM calls -- a grounded
        # quote cannot prove class membership for a closed vocabulary.
        calls = {"n": 0}

        def tech_fn(messages, **kw):
            calls["n"] += 1
            return json.dumps({"confirmed": [
                {"class": "weapons_smoking",
                 "quote": "reaching for the lever by the door"}]})

        kills, discarded = ORR.triage_hard_findings(
            [self._finding("weapons_smoking",
                           "the coils start to smoke like doom")],
            script=self._SCRIPT, technical_fn=tech_fn)
        assert not kills and len(discarded) == 1
        assert calls["n"] == 0, "lexicon_only class must never confirm"

    def test_confirm_drop_discards(self):
        fn = _seq_fn(json.dumps({"confirmed": []}))
        kills, discarded = ORR.triage_hard_findings(
            [self._finding("news_source_framing", "sounds like a teaser")],
            script=self._SCRIPT, technical_fn=fn)
        assert not kills and len(discarded) == 1

    def test_confirm_grounded_quote_kills(self):
        fn = _seq_fn(json.dumps({"confirmed": [
            {"class": "news_source_framing",
             "quote": "This has been SIGNAL LOST."}]}))
        kills, discarded = ORR.triage_hard_findings(
            [self._finding("news_source_framing", "framed as a broadcast")],
            script=self._SCRIPT, technical_fn=fn)
        assert len(kills) == 1 and not discarded
        assert "SIGNAL LOST" in kills[0][1]

    def test_confirm_ungrounded_quote_exhausts_to_discard(self):
        # The confirm judge invents a quote that is NOT in the script:
        # the post-validator rejects it, the bounded ladder exhausts,
        # and the finding is discarded (never a kill without evidence).
        fn = _seq_fn(json.dumps({"confirmed": [
            {"class": "news_source_framing",
             "quote": "and now tonight's factual account"}]}))
        kills, discarded = ORR.triage_hard_findings(
            [self._finding("news_source_framing",
                           "framed as though it were factual")],
            script=self._SCRIPT, technical_fn=fn)
        assert not kills and len(discarded) == 1


# ---------------------------------------------------------------------------
# 7. Provenance surfaces
# ---------------------------------------------------------------------------

class TestProvenance:
    def test_news_payload_legacy_byte_shape(self):
        outline = SimpleNamespace(title="T", premise="P")
        entry = json.loads(W._build_news_payload(outline, "seed", "rss"))[0]
        assert "origin_label" not in entry
        assert entry["source"] == "RSS Auto-Fetch"
        assert entry["headline"] == "T"

    def test_news_payload_original_labels(self):
        outline = SimpleNamespace(title="Outline Title", premise="P")
        entry = json.loads(W._build_news_payload(
            outline, "seed", "original_llm",
            source_label="Original (LLM)",
            origin_label="STORY ORIGIN",
            headline_override="Final Title",
        ))[0]
        assert entry["source"] == "Original (LLM)"
        assert entry["origin_label"] == "STORY ORIGIN"
        assert entry["headline"] == "Final Title"

    def test_hud_parse_reads_origin_label(self):
        from nodes import video_engine as VE
        news_used = json.dumps([{"headline": "H",
                                 "origin_label": "STORY ORIGIN"}])
        led = {"cast": [], "meta": {}, "lines": []}
        data = VE._parse_hud_data(
            "T", led, {}, "style", "genre", news_used, 10.0, 640, 360)
        assert data["news_origin_label"] == "STORY ORIGIN"
        assert data["news_seeds"] == ["H"]

    def test_hud_parse_legacy_default(self):
        from nodes import video_engine as VE
        data = VE._parse_hud_data(
            "T", {"cast": [], "meta": {}, "lines": []}, {}, "s", "g",
            json.dumps([{"headline": "H"}]), 10.0, 640, 360)
        assert data["news_origin_label"] == ""
