"""The printed SOURCE line on the credits roll follows the episode row.

Operator pick 2026-09-18: a bank-by-language matrix. Per-bank sentences live
in banks.json as scalar `credits_source_line_<iso>` keys; the Python sentences
(provenance credit, the "freely adapted" wrap, My Story's credit, the
writer tail's models line) and the roll's SOURCE labels are row `credits`
keys. English and no meta are byte-identical to the old literals. CPU only.
"""
from __future__ import annotations

import inspect

import pytest

from nodes import _otr_episode_languages as EL
from nodes import _otr_provenance as PROV
from nodes import _otr_story_input as SI
from nodes import _otr_story_routing as RT
from nodes import _otr_verbatim_lane as VL

ROWS = [row for row in EL.load_registry()[0] if row.admitted]
NON_ENGLISH = [row for row in ROWS if row.iso != "en"]
BANKS_WITH_LINE = ("original", "scifi_news_pro", "my_story")


# --------------------------------------------------------------------------- #
# the matrix
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize("bank_id", BANKS_WITH_LINE)
def test_every_bank_default_line_has_every_non_english_row(bank_id):
    defaults = RT.get_bank(bank_id).defaults or {}
    assert defaults["credits_source_line"].strip()
    for row in NON_ENGLISH:
        line = defaults["credits_source_line_" + row.iso]
        assert line.strip(), (bank_id, row.iso)
        assert line != defaults["credits_source_line"], (bank_id, row.iso)


def test_the_writer_reads_the_matrix_by_iso_and_falls_back_to_the_default():
    from nodes import OTR_LedgerScriptWriter as W
    src = inspect.getsource(W.OTR_LedgerScriptWriter.run)
    block = src[src.index('"credits_source_line_" + _EPLANG.iso_from_meta(meta)'):]
    block = block[:block.index('meta["credits_source_line"] = _credits_line')]
    assert "or _credits_line" in block


# --------------------------------------------------------------------------- #
# the Python sentences
# --------------------------------------------------------------------------- #


def test_english_and_no_meta_are_byte_identical_for_the_provenance_credit():
    cases = [
        ({"status": "public_domain_us", "source_label": "Hamlet"},
         "adapted from Hamlet (public domain)"),
        ({"status": "public_domain_us"}, "adapted from a public domain work"),
        ({"status": "cc0", "source_label": "X"}, "adapted from X (CC0 / public domain)"),
        ({"status": "research_only", "source_label": "X"},
         "adapted from X (research use only)"),
        ({"status": "research_only"},
         "adapted from a source cleared for research use only"),
        ({"status": "licensed_noncommercial", "source_label": "Macbeth",
          "license_label": "CC BY-NC 3.0"},
         "adapted from Macbeth, used under CC BY-NC 3.0"),
        ({"status": "licensed_noncommercial", "license_label": "CC BY-NC 3.0"},
         "used under CC BY-NC 3.0"),
        ({"status": "licensed_commercial", "source_label": "Macbeth"},
         "adapted from Macbeth"),
        ({"status": "synthetic"},
         "an original story generated by machine for this broadcast"),
        ({"status": "mystery"}, ""),
    ]
    for prov, want in cases:
        assert PROV.printed_credit_line(prov) == want, prov
        assert PROV.printed_credit_line(prov, episode_meta={"episode_language": "en"}) == want
        assert PROV.printed_credit_line(prov, episode_meta={}) == want


def test_the_provenance_credit_follows_the_row():
    prov = {"status": "public_domain_us", "source_label": "Hamlet"}
    assert PROV.printed_credit_line(prov, episode_meta={"episode_language": "es"}) \
        == "adaptado de Hamlet (dominio público)"
    assert PROV.printed_credit_line({"status": "synthetic"},
                                    episode_meta={"episode_language": "ja"}) \
        == "この放送のために機械が生成したオリジナル作品"


def test_the_freely_wrap_is_byte_identical_in_english_and_follows_the_row():
    assert VL.non_verbatim_credit_line("adapted from Macbeth (CC BY-NC 3.0)") == \
        "freely adapted from Macbeth (CC BY-NC 3.0)"
    assert VL.non_verbatim_credit_line("used under CC BY-NC 3.0") == \
        "freely adapted from the source; used under CC BY-NC 3.0"
    assert VL.non_verbatim_credit_line("") == "freely adapted from the source"
    es = {"episode_language": "es"}
    assert VL.non_verbatim_credit_line("adaptado de Macbeth (CC BY-NC 3.0)", episode_meta=es) \
        == "libremente adaptado de Macbeth (CC BY-NC 3.0)"
    assert VL.non_verbatim_credit_line("bajo licencia CC BY-NC 3.0", episode_meta=es) \
        == "libremente adaptado de la fuente; bajo licencia CC BY-NC 3.0"
    hi = {"episode_language": "hi"}
    assert VL.non_verbatim_credit_line("Macbeth से रूपांतरित (CC BY-NC 3.0)", episode_meta=hi) \
        == "Macbeth से रूपांतरित (CC BY-NC 3.0) (मुक्त रूपांतरण)"


def test_my_story_printed_credit_follows_the_row():
    assert SI.credits_source_line("Ada Byron") == \
        "a story by Ada Byron, produced by machine for this broadcast"
    assert SI.credits_source_line("") == SI.ANONYMOUS_CREDIT
    assert SI.credits_source_line("Ada Byron", episode_meta={"episode_language": "en"}) == \
        "a story by Ada Byron, produced by machine for this broadcast"
    assert SI.credits_source_line("Ada Byron", episode_meta={"episode_language": "fr"}) == \
        "une histoire de Ada Byron, produite par machine pour cette émission"
    receipt = SI.attribution_receipt("Ada Byron", episode_meta={"episode_language": "fr"})
    assert receipt["credits_source_line"].startswith("une histoire de Ada Byron")


def test_the_models_line_is_a_row_template_with_the_english_literal():
    en = EL.credits_or_english(None)
    assert en["credit_models_used"].format(models="a, b") == \
        "Story generation models used: a, b"
    assert en["credit_models_none"] == "none recorded"
    from nodes import _otr_writer_tail as tail
    src = inspect.getsource(tail._stamp_model_call_provenance)
    # The row template is the primary path; the English literal survives
    # only as the fallback inside the except.
    assert 'credit_models_used' in src and 'credit_models_none' in src
    assert src.count('"Story generation models used: "') == 1
    assert src.index("credit_models_used") < src.index('"Story generation models used: "')
    assert "except Exception" in src[:src.index('"Story generation models used: "')]


def test_the_roll_labels_are_row_values():
    from nodes import otr_credits_roll as roll
    src = inspect.getsource(roll)
    assert '">> SOURCE: %s"' not in src
    assert '">> SOURCE INTERCEPT: %s"' not in src
    assert 'chrome["source_label"]' in src
    assert 'chrome["source_intercept_label"]' in src
    en = EL.credits_or_english(None)
    assert en["source_label"] == "SOURCE"
    assert en["source_intercept_label"] == "SOURCE INTERCEPT"


# --------------------------------------------------------------------------- #
# every row formats every template
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize("row", ROWS, ids=[r.iso for r in ROWS])
def test_every_row_formats_every_printed_template(row):
    meta = {"episode_language": row.iso}
    for status in ("public_domain_us", "cc0", "research_only", "synthetic",
                   "licensed_noncommercial"):
        with_src = PROV.printed_credit_line(
            {"status": status, "source_label": "Work", "license_label": "L"},
            episode_meta=meta)
        assert with_src.strip(), (row.iso, status)
        if status != "synthetic":
            assert "Work" in with_src, (row.iso, status)
        assert PROV.printed_credit_line({"status": status, "license_label": "L"},
                                        episode_meta=meta).strip()
    wrapped = VL.non_verbatim_credit_line(with_src, episode_meta=meta)
    assert wrapped.strip() and wrapped != with_src, row.iso
    assert VL.non_verbatim_credit_line("", episode_meta=meta).strip()
    assert "Ada" in SI.credits_source_line("Ada", episode_meta=meta)
    assert SI.credits_source_line("", episode_meta=meta).strip()
    assert "m1" in row.credits["credit_models_used"].format(models="m1")


def test_the_provenance_fallback_templates_equal_the_english_row():
    """The except-path literals and the registry's English row are the same
    ten sentences; a drift between them would be invisible on English."""
    english = EL.credits_or_english(None)
    for key, value in PROV._ENGLISH_CREDIT_TEMPLATES.items():
        assert english[key] == value, key


def test_credits_or_english_degrades_to_english():
    assert EL.credits_or_english({"episode_language": "tlh"}) == EL.credits_or_english(None)
    assert EL.credits_or_english({"episode_language": "es"})["source_label"] == "FUENTE"


def test_an_unreadable_registry_never_costs_a_printed_credit(monkeypatch):
    """Every printed-credit site keeps its English literal when the registry
    itself cannot be read -- a label may never fail a roll or a run."""
    def _broken(*_a, **_k):
        raise EL.EpisodeLanguageError("registry unreadable")

    monkeypatch.setattr(EL, "row_by_label", _broken)
    monkeypatch.setattr(EL, "row_from_meta", _broken)
    assert EL.credits_or_english(None) == {}
    assert EL.credits_or_english({"episode_language": "es"}) == {}
    prov = {"status": "public_domain_us", "source_label": "Hamlet"}
    assert PROV.printed_credit_line(prov, episode_meta={"episode_language": "es"}) == \
        "adapted from Hamlet (public domain)"
    assert VL.non_verbatim_credit_line("adapted from X", episode_meta={"episode_language": "es"}) \
        == "freely adapted from X"
    assert SI.credits_source_line("Ada", episode_meta={"episode_language": "es"}) == \
        "a story by Ada, produced by machine for this broadcast"
    from nodes import otr_credits_roll as roll
    chrome = roll._credits_chrome({"episode_language": "es"})
    assert set(chrome) == set(EL._REQUIRED_CREDITS)
    assert all(str(v).strip() for v in chrome.values())
    assert chrome["source_label"] == "SOURCE"
    from nodes import _otr_writer_tail as tail
    src = inspect.getsource(tail._stamp_model_call_provenance)
    # The tail keeps its English literal inside an except around the lookup.
    assert '"Story generation models used: " + (' in src
    assert src.index("credits_or_english(meta)") < src.index('"Story generation models used: " + (')
    assert "except Exception" in src[src.index("credits_or_english(meta)"):]
