"""original_radio lane -- registry, dispatch, creative front, and provenance.

CHUNK B tests (ARCHITECTURE_V4 + R2_CODING_PLAN + R3 deltas + r4 pins,
2026-07-09). Pure Python; no GPU, no real LLM, no network: every LLM call
is a canned-JSON fake through the real structured_call ladder.
"""
from __future__ import annotations

import dataclasses
import json
import sys
from pathlib import Path
from types import SimpleNamespace

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from nodes import _otr_original_radio as ORR  # noqa: E402
from nodes import _otr_source_payload as OSP  # noqa: E402
from nodes import _otr_story_routing as ROUTING  # noqa: E402
from nodes import OTR_LedgerScriptWriter as W  # noqa: E402
from nodes._otr_structured_call import StructuredCallFailedError  # noqa: E402


@pytest.fixture(autouse=True)
def _fresh_registry():
    ROUTING._REGISTRY = None
    yield
    ROUTING._REGISTRY = None


# ---------------------------------------------------------------------------
# 1. Registry: rows + sweep (runnable-on-build set is live)
# ---------------------------------------------------------------------------

class TestRegistry:
    def test_real_registry_loads_with_original_row(self):
        ids = ROUTING.list_bank_ids()
        assert "original" in ids
        assert ids[-1] == "custom_source_bank"  # "+ Add Your Own" stays last

    def test_bank_row_shape(self):
        bank = ROUTING.get_bank("original")
        assert bank.runnable is True
        assert bank.fetcher == "" and bank.interpreter == ""
        assert bank.default_story_pipeline == "original_multi_pass"
        d = bank.defaults
        assert d.get("hud_origin_label") == "STORY ORIGIN"
        assert "generated by machine" in d.get("credits_source_line", "")
        assert "coda_mode" not in d  # V4 lock 8: dead config class

    def test_pipeline_row_shape(self):
        pipe = ROUTING.get_pipeline("original_multi_pass")
        assert pipe.executable is True          # sweep 4b elif demands it
        assert pipe.requires_source_contract is False
        assert pipe.declared_seams == frozenset({
            "original_concept_system", "original_select_system",
            "original_brief_system",
        })

    def test_pack_carries_12_stages_and_required_subset(self):
        bank = ROUTING.get_bank("original")
        pack = ROUTING.resolve_story_pack("original")
        assert len(pack.prompt_stages) == 12
        assert set(bank.required_seams) <= set(pack.prompt_stages)
        for seam in (
            "original_concept_system",
            "original_select_system",
            "original_brief_system",
        ):
            assert pack.prompt_stages[seam].strip()

    def test_sweep_demands_executable_true(self):
        # The r2 M2 pin, both directions: the REAL set passes (loaded
        # above); a fixture with executable:false raises the 4b elif.
        reg = ROUTING._ensure_loaded()
        bad_pipe = dataclasses.replace(
            reg.pipelines["original_multi_pass"], executable=False)
        pipelines = dict(reg.pipelines)
        pipelines["original_multi_pass"] = bad_pipe
        # Full real bank map: the sweep also audits the packs DIRECTORY
        # against the bank ids, so a single-bank fixture dies earlier.
        with pytest.raises(ROUTING.RegistryValidationError,
                           match="runner to exist"):
            ROUTING._sweep_and_crossref(dict(reg.banks), pipelines)

    def test_custom_bank_still_dies_at_run_gate(self):
        with pytest.raises(ROUTING.StoryBankNotRunnableError):
            ROUTING.require_runnable_bank("custom_source_bank")


# ---------------------------------------------------------------------------
# 2. Dispatch helper (r4 P8)
# ---------------------------------------------------------------------------

class TestDispatch:
    def test_bank_shape_test(self):
        assert W._bank_has_no_source_contract(
            ROUTING.get_bank("original")) is True
        assert W._bank_has_no_source_contract(
            ROUTING.get_bank("media_archive")) is False
        # custom is empty-empty but runnable:false -> NOT the original
        # lane: a direct _resolve_inputs call keeps its pinned LOUD
        # SourceContractMissingError path (chunk3 test).
        assert W._bank_has_no_source_contract(
            ROUTING.get_bank("custom_source_bank")) is False


# ---------------------------------------------------------------------------
# 3. A-branch payload (spark digest; operator_hint rides source_meta)
# ---------------------------------------------------------------------------

class TestResolveInputsOriginal:
    def test_payload_contract_and_sidecars(self, monkeypatch):
        monkeypatch.setenv("OTR_ORIGINAL_SEED", "pin-42")
        r = W._resolve_inputs(
            source_bank="original", custom_premise="  a night ferry  ",
        )
        art = r["news_article"]
        assert set(art) == OSP.SOURCE_PAYLOAD_KEYS
        assert art["source"] == "Original (LLM)"
        assert art["seed_text"].strip()
        assert r["seed_source"] == "original_llm"
        sm = r["source_meta"]
        assert sm["kind"] == "original_llm"
        assert set(sm["spark_atoms"]) == set(ORR.DECK_AXES)
        assert sm["operator_hint"] == "a night ferry"   # r4 P2: not payload
        assert "operator_hint" not in art
        assert r["source_rights"]["license_label"] == "synthetic original"

    def test_seeded_draw_is_reproducible(self, monkeypatch):
        monkeypatch.setenv("OTR_ORIGINAL_SEED", "pin-42")
        a = W._resolve_inputs(source_bank="original")
        b = W._resolve_inputs(source_bank="original")
        assert (a["source_meta"]["spark_atoms"]
                == b["source_meta"]["spark_atoms"])

# ---------------------------------------------------------------------------
# 4. Deck + creative front (canned-JSON fakes through the real ladder)
# ---------------------------------------------------------------------------

def _seq_fn(*replies):
    it = iter(replies)
    last = replies[-1]

    def _fn(messages, **kw):
        return next(it, last)
    return _fn


_CONCEPT_JSON = json.dumps({"pitches": [
    {"logline": f"Pitch {i}: a ferrywoman conceals a pawn ticket at the lock",
     "hook": "who redeems it", "radio_device": "a silence where a reply should be",
     "cast_sketch": [{"name": "MARA", "role": "ferrywoman"},
                     {"name": "ELLIS", "role": "lock keeper"}]}
    for i in range(3)
]})
_SELECT_JSON = json.dumps({
    "selected_index": 1,
    "pitch": {"logline": "MARA conceals a pawn ticket from ELLIS at the lock",
              "hook": "the ticket names no item",
              "radio_device": "a silence where a reply should be"},
    "cast": [
        {"name": "MARA", "want": "to keep the ticket", "pressure": "the toll",
         "relationship": "works the lock with ELLIS"},
        {"name": "ELLIS", "want": "an honest ledger", "pressure": "the audit",
         "relationship": "trusts MARA too far"},
    ],
    "selection_rationale": "two voices, one object, audible standoff",
})
_BRIEFS_JSON = json.dumps({
    "casting_brief": ("MARA, a ferrywoman: level voice that shortens when the"
                      " pawn ticket comes near. ELLIS, a lock keeper: dry,"
                      " precise, counts everything twice."),
    "script_brief": ("At the canal lock, MARA conceals a pawn ticket that"
                     " names no item; ELLIS balances a ledger that will not"
                     " close. The episode opens at dusk and ends when the"
                     " ticket is read aloud."),
    "key_terms": ["pawn ticket", "ELLIS"],
})


class TestCreativeFront:
    def test_deck_loads_and_draws(self):
        deck = ORR.load_spark_deck()
        draw = ORR.draw_spark_atoms(deck)
        assert set(draw.atoms) == set(ORR.DECK_AXES)
        assert draw.digest.strip() and draw.deck_version == "v1"

    def _pack(self):
        return ROUTING.resolve_story_pack("original")

    def test_front_green_and_contract(self):
        briefs, delta = ORR.build_original_briefs(
            spark_atoms={"place": "the lock"},
            num_characters=2,
            creative_fn=_seq_fn(_CONCEPT_JSON, _SELECT_JSON),
            technical_fn=_seq_fn(_BRIEFS_JSON),
            creative_model_id="c-model", technical_model_id="t-model",
            pack=self._pack(),
        )
        dump = OSP.validate_interpreter_result(briefs, origin="test")
        assert dump["news_close_brief"] == ""       # V4 lock 1
        assert dump["key_terms"] == ["pawn ticket", "ELLIS"]
        assert delta["selected_concept"]["selected_index"] == 1
        assert len(delta["pitches"]) == 3
        assert delta["model_ids"] == {"creative": "c-model",
                                      "technical": "t-model"}

    def test_wrong_cast_count_exhausts(self):
        bad = json.dumps({"pitches": json.loads(_CONCEPT_JSON)["pitches"]})
        with pytest.raises(StructuredCallFailedError):
            ORR.build_original_briefs(
                spark_atoms={"place": "the lock"},
                num_characters=3,   # pitches carry 2 -> gate rejects x3
                creative_fn=_seq_fn(bad),
                technical_fn=_seq_fn(_BRIEFS_JSON),
                pack=self._pack(),
            )

    def test_unsupported_key_term_is_deleted_without_another_model_call(self):
        calls = {"n": 0}
        payload = json.dumps({
            **json.loads(_BRIEFS_JSON),
            "key_terms": ["pawn ticket", "ZEPPELIN"],
        })

        def tech_fn(messages, **kw):
            calls["n"] += 1
            return payload

        briefs, _ = ORR.build_original_briefs(
            spark_atoms={"place": "the lock"},
            num_characters=2,
            creative_fn=_seq_fn(_CONCEPT_JSON, _SELECT_JSON),
            technical_fn=tech_fn,
            pack=self._pack(),
        )
        assert briefs.key_terms == ["pawn ticket"]
        assert calls["n"] == 1

    def test_key_term_grounds_across_a_line_wrap(self):
        # A2 normalization (live-smoke hardening 2026-07-09): the corpus
        # joins fields with newlines and a field may wrap a phrase across
        # a line break; a key_term copied verbatim must still ground.
        sel = json.loads(_SELECT_JSON)
        sel["pitch"]["logline"] = (
            "MARA conceals a pawn\nticket from ELLIS at the lock")
        briefs, _ = ORR.build_original_briefs(
            spark_atoms={"place": "the lock"},
            num_characters=2,
            creative_fn=_seq_fn(_CONCEPT_JSON, json.dumps(sel)),
            technical_fn=_seq_fn(_BRIEFS_JSON),
            pack=self._pack(),
        )
        assert briefs.key_terms == ["pawn ticket", "ELLIS"]

    def test_ungrounded_key_term_pruned_deterministically(self):
        # Unsupported optional proof terms are dropped after the first
        # structurally valid response, with no second technical call.
        calls = {"n": 0}
        bad = json.dumps({
            **json.loads(_BRIEFS_JSON),
            "key_terms": ["pawn ticket", "ELLIS", "grieving mother"],
        })

        def tech_fn(messages, **kw):
            calls["n"] += 1
            return bad

        briefs, _ = ORR.build_original_briefs(
            spark_atoms={"place": "the lock"},
            num_characters=2,
            creative_fn=_seq_fn(_CONCEPT_JSON, _SELECT_JSON),
            technical_fn=tech_fn,
            pack=self._pack(),
        )
        assert briefs.key_terms == ["pawn ticket", "ELLIS"]
        assert calls["n"] == 1, "prune must not spend an LLM repair call"

    def test_zero_grounded_key_terms_is_valid(self):
        calls = {"n": 0}
        payload = json.dumps({
            **json.loads(_BRIEFS_JSON),
            "key_terms": ["ZEPPELIN"],
        })

        def tech_fn(messages, **kw):
            calls["n"] += 1
            return payload

        briefs, _ = ORR.build_original_briefs(
            spark_atoms={"place": "the lock"},
            num_characters=2,
            creative_fn=_seq_fn(_CONCEPT_JSON, _SELECT_JSON),
            technical_fn=tech_fn,
            pack=self._pack(),
        )
        assert briefs.key_terms == []
        assert calls["n"] == 1

    def test_nonempty_close_brief_is_hardwired_empty_without_retry(self):
        calls = {"n": 0}
        payload = json.dumps({
            **json.loads(_BRIEFS_JSON),
            "news_close_brief": "tonight's tale was generated",
        })

        def tech_fn(messages, **kw):
            calls["n"] += 1
            return payload

        briefs, _ = ORR.build_original_briefs(
            spark_atoms={"place": "the lock"},
            num_characters=2,
            creative_fn=_seq_fn(_CONCEPT_JSON, _SELECT_JSON),
            technical_fn=tech_fn,
            pack=self._pack(),
        )
        assert briefs.news_close_brief == ""
        assert calls["n"] == 1

    def test_one_pitch_is_valid_and_selected_dynamically(self):
        concept = json.loads(_CONCEPT_JSON)
        concept["pitches"] = concept["pitches"][:1]
        selected = json.loads(_SELECT_JSON)
        selected["selected_index"] = 0
        briefs, delta = ORR.build_original_briefs(
            spark_atoms={"place": "the lock"},
            num_characters=2,
            creative_fn=_seq_fn(json.dumps(concept), json.dumps(selected)),
            technical_fn=_seq_fn(_BRIEFS_JSON),
            pack=self._pack(),
        )
        assert briefs.script_brief
        assert len(delta["pitches"]) == 1
        assert delta["selected_concept"]["selected_index"] == 0


# ---------------------------------------------------------------------------
# 5. Interpreter adapter (D.2 shape + D3 restamp)
# ---------------------------------------------------------------------------

class TestInterpreterAdapter:
    def test_adapter_runs_and_restamps_both_surfaces(self):
        resolved = {
            "source_meta": {"kind": "original_llm",
                            "spark_atoms": {"place": "the lock"}},
            "num_characters": 2,
            "creative_writing_model": "c-model",
        }
        meta = {"source_meta": dict(resolved["source_meta"])}
        adapter = W._make_original_interpreter(
            creative_fn=_seq_fn(_CONCEPT_JSON, _SELECT_JSON),
            resolved=resolved, meta=meta,
        )
        bank = ROUTING.get_bank("original")
        briefs = adapter(bank=bank, payload={"ignored": "yes"},
                         technical_fn=_seq_fn(_BRIEFS_JSON),
                         model_id="t-model")
        assert briefs.casting_brief
        # r3 D3: the delta reached BOTH surfaces.
        for surface in (resolved["source_meta"], meta["source_meta"]):
            assert "selected_concept" in surface
            assert surface["model_ids"]["technical"] == "t-model"

    def test_adapter_without_atoms_fails_loud(self):
        adapter = W._make_original_interpreter(
            creative_fn=_seq_fn(_CONCEPT_JSON), resolved={"source_meta": {},
            "num_characters": 2, "creative_writing_model": "c"}, meta={},
        )
        with pytest.raises(ORR.OriginalBriefsError, match="spark_atoms"):
            adapter(bank=ROUTING.get_bank("original"), payload={},
                    technical_fn=_seq_fn(_BRIEFS_JSON), model_id="t")


# ---------------------------------------------------------------------------\n# 6. Provenance surfaces\n# ---------------------------------------------------------------------------

class TestProvenance:
    def test_news_payload_legacy_byte_shape(self):
        outline = SimpleNamespace(title="T", premise="P")
        entry = json.loads(W._build_news_payload(outline, "seed", "rss"))[0]
        assert "origin_label" not in entry
        assert entry["source"] == "RSS Auto-Fetch"
        assert entry["headline"] == "T"

    def test_news_payload_original_labels(self):
        outline = SimpleNamespace(title="Outline Title", premise="P")
        entry = json.loads(W._build_news_payload(
            outline, "seed", "original_llm",
            source_label="Original (LLM)",
            origin_label="STORY ORIGIN",
            headline_override="Final Title",
        ))[0]
        assert entry["source"] == "Original (LLM)"
        assert entry["origin_label"] == "STORY ORIGIN"
        assert entry["headline"] == "Final Title"

    def test_hud_parse_reads_origin_label(self):
        from nodes import video_engine as VE
        news_used = json.dumps([{"headline": "H",
                                 "origin_label": "STORY ORIGIN"}])
        led = {"cast": [], "meta": {}, "lines": []}
        data = VE._parse_hud_data(
            "T", led, {}, "style", "genre", news_used, 10.0, 640, 360)
        assert data["news_origin_label"] == "STORY ORIGIN"
        assert data["news_seeds"] == ["H"]

    def test_hud_parse_legacy_default(self):
        from nodes import video_engine as VE
        data = VE._parse_hud_data(
            "T", {"cast": [], "meta": {}, "lines": []}, {}, "s", "g",
            json.dumps([{"headline": "H"}]), 10.0, 640, 360)
        assert data["news_origin_label"] == ""
