r"""Per-character outfit LOCK -- LLM-generated from the character + story brief, then
locked across every beat.

Operator directives (2026-06-16):
  * The outfit MUST link with the character AND the story brief (not a generic pick).
  * Generated by an LLM, after the whole script is done (the script/cast/brief are all in
    the ledger by the image phase, so _appearance_for_char -- which feeds every image
    prompt -- has full context).
  * NO FALLBACK. If the LLM can't produce a valid story-based outfit, FAIL LOUD. A generic
    outfit is worse than a clear failure.

The outfit is generated ONCE per character, cached on the cast row, and reused for every
beat + re-render. Opt-in: default OFF (env OTR_OUTFIT_LOCK != "1") -> appearance unchanged
(byte-identical). Stdlib-only at import time (the LLM factory is imported lazily).
"""
from __future__ import annotations

import logging
import os
import re

_LOG = logging.getLogger("OTR.wardrobe")

FLAG_ENV = "OTR_OUTFIT_LOCK"
OUTFIT_MAX_CHARS = 90

# Clothing-specific, low-collision tokens. Used to (a) skip locking when the appearance
# already names clothing, and (b) sanity-check the LLM actually returned an outfit.
_CLOTHING_TOKENS = (
    "wearing", "dressed", "overcoat", "trench coat", "jacket", "shirt", "uniform",
    "blazer", "waistcoat", "gown", "sweater", "turtleneck", "trousers", "slacks",
    "scarf", "blouse", "cardigan", "tunic", "suspenders", "coat", "suit", "dress",
    "robe", "vest", "boots", "gloves", "apron", "hat", "cloak", "poncho", "duster",
)
_REFUSAL_TOKENS = (
    "as an ai", "i cannot", "i can't", "cannot provide", "i'm sorry", "i am sorry",
    "sorry,", "unable to", "i don't have", "here is", "here's",
)


class WardrobeError(RuntimeError):
    """Raised when the outfit lock is ON but no valid story-based outfit could be made.
    Intentionally LOUD (operator directive: no silent generic fallback)."""


def enabled() -> bool:
    """True when the operator opted in via the env flag."""
    return str(os.environ.get(FLAG_ENV, "")).strip() == "1"


_CLOTHING_RE = re.compile(
    r"\b(" + "|".join(re.escape(t) for t in _CLOTHING_TOKENS) + r")\b", re.IGNORECASE)


def has_clothing(text: str) -> bool:
    """Does the text already name an outfit? Word-boundary match so 'suit' hits 'a suit'
    but NOT 'suitable'/'pursuit'."""
    return bool(_CLOTHING_RE.search(str(text or "")))


def _cast_row(ledger, char_id):
    for c in (ledger or {}).get("cast") or []:
        if isinstance(c, dict) and str(c.get("char_id") or "") == str(char_id):
            return c
    return None


def _char_desc(row) -> str:
    if not isinstance(row, dict):
        return ""
    for k in ("character_description", "appearance", "description", "portrait_prompt"):
        v = row.get(k)
        if isinstance(v, str) and v.strip():
            return v.strip()
    return ""


def _brief_context(ledger) -> str:
    """Short story-world context for the outfit prompt (setting/logline from the brief)."""
    meta = (ledger or {}).get("meta") or {}
    terms = meta.get("story_brief_terms") if isinstance(meta, dict) else None
    if isinstance(terms, dict):
        for k in ("setting", "world", "logline", "premise", "atmosphere"):
            v = terms.get(k)
            if isinstance(v, str) and v.strip():
                return v.strip()[:240]
            if isinstance(v, list) and v:
                return ", ".join(str(x).strip() for x in v if str(x).strip())[:240]
    sb = meta.get("story_brief") if isinstance(meta, dict) else None
    if isinstance(sb, str) and sb.strip():
        return sb.strip()[:240]
    return ""


def build_outfit_messages(name: str, desc: str, brief: str) -> list:
    system = (
        "You assign ONE fixed outfit for a recurring character in a vintage radio drama, "
        "consistent with BOTH the character and the story's world/era. Output ONLY a short "
        "outfit phrase (<= 80 chars): garments + materials, period- and story-appropriate. "
        "No names, no scene/background, no preamble, no quotes. The character wears this in "
        "EVERY shot.")
    user = ("Story world: %s\nCharacter: %s -- %s\nOutfit:"
            % (brief or "(unspecified)", name or "the character",
               desc or "(no description)"))
    return [{"role": "system", "content": system},
            {"role": "user", "content": user}]


def _first_line(raw: str) -> str:
    s = str(raw or "").strip().strip('"').strip()
    for ln in s.splitlines():
        ln = ln.strip().strip('"').lstrip("-*0123456789. ").strip()
        if ln:
            return ln
    return s


def _validate_outfit(text: str) -> tuple[bool, str]:
    t = str(text or "").strip()
    if not t:
        return False, "empty"
    if len(t) > OUTFIT_MAX_CHARS:
        return False, "over_budget"
    low = t.lower()
    if any(r in low for r in _REFUSAL_TOKENS):
        return False, "refusal_or_preamble"
    if not has_clothing(t):
        return False, "not_an_outfit"
    return True, "ok"


def _generate_outfit(ledger, char_id: str, row) -> str:
    """LLM-generate a story+character outfit. Raises WardrobeError on ANY failure --
    NO silent fallback (operator directive)."""
    name = str((row or {}).get("name") or char_id)
    desc = _char_desc(row)
    brief = _brief_context(ledger)
    try:
        from ._otr_motion_clause import make_writer_generate_fn  # type: ignore
    except ImportError:  # pragma: no cover -- flat import
        from _otr_motion_clause import make_writer_generate_fn  # type: ignore
    generate_fn = make_writer_generate_fn()
    if generate_fn is None:
        _LOG.error("[OTR.wardrobe] outfit LLM unavailable for %s (lock ON) -- FAIL LOUD",
                   char_id)
        raise WardrobeError("outfit LLM unavailable for %s (OTR_OUTFIT_LOCK is ON)"
                            % char_id)
    try:
        # LLM slot: creative -- per-character story-based outfit (locked once, reused)
        raw = generate_fn(build_outfit_messages(name, desc, brief),
                          temperature=0.4, max_new_tokens=48, stop=None)
    except Exception as exc:  # noqa: BLE001
        _LOG.error("[OTR.wardrobe] outfit LLM call failed for %s: %r -- FAIL LOUD",
                   char_id, exc)
        raise WardrobeError("outfit LLM call failed for %s: %r" % (char_id, exc))
    outfit = _first_line(raw)
    ok, reason = _validate_outfit(outfit)
    if not ok:
        _LOG.error("[OTR.wardrobe] no valid story-based outfit for %s (%s): %.80r -- "
                   "FAIL LOUD", char_id, reason, outfit)
        raise WardrobeError("no valid story-based outfit for %s (%s)" % (char_id, reason))
    _LOG.warning("[OTR.wardrobe] %s outfit locked: %s", char_id, outfit)
    return outfit


def locked_outfit(char_id: str, ledger=None) -> str:
    """The character's LOCKED outfit: cached on the cast row, else LLM-generated once
    (raises WardrobeError if the LLM can't make a valid story-based outfit -- no fallback).
    The resolved outfit is cached back onto the cast row so every beat + re-render match."""
    row = _cast_row(ledger, char_id)
    cached = row.get("_wardrobe_lock") if isinstance(row, dict) else None
    if isinstance(cached, str) and cached.strip():
        return cached.strip()
    outfit = _generate_outfit(ledger, char_id, row)
    if isinstance(row, dict):
        row["_wardrobe_lock"] = outfit
    return outfit


def apply_wardrobe(appearance: str, char_id: str, ledger=None) -> str:
    """Append the LOCKED outfit to an appearance, IFF the lock is enabled, a char_id is
    present, and the appearance does not already name clothing. Default OFF -> unchanged.
    Raises WardrobeError (LOUD) when enabled but no valid story-based outfit can be made."""
    app = str(appearance or "")
    if not enabled() or not str(char_id or "").strip():
        return app
    if has_clothing(app):
        return app
    outfit = locked_outfit(char_id, ledger)
    if not app.strip():
        return outfit
    return app.rstrip().rstrip(".,;: ") + ", wearing " + outfit
