"""
video_composite.py  --  OTR_VideoComposite ComfyUI node
=======================================================

In-graph ffmpeg-driven episode compositor. Replaces
``scripts/render_episode_concat.py`` for production runs; the CLI
script stays as an ad-hoc smoke tool.

Layered output (per Jeffrey's spec, locked 2026-04-27):

    1920x1080 canvas, 25 fps
    ┌──────────┬──────────────┬──────────┐
    │          │              │          │
    │ proc gen │   HuMo       │ proc gen │
    │ (left)   │   624x1080   │ (right)  │
    │          │              │          │
    └──────────┴──────────────┴──────────┘
     648 px      624 px         648 px

    + proc gen layer additive-blended on top at 50% opacity
      so CRT visualizer waveforms / spectrum bars glow over HuMo
      face during dialogue and fill the canvas during silence

The proc gen mp4 produced by OTR_SignalLostVideo carries audio-
reactive CRT visuals + the full episode audio. This node uses it
as both the base layer AND the audio source for the final mux. No
separate audio mux step is required.

Inputs:
    procgen_video_path  STRING  Path to the SignalLostVideo output
                                mp4 (full-episode audio-reactive
                                CRT base layer, 1920x1080 @ 24 fps,
                                AAC 48 kHz audio embedded).
    clips_dir           STRING  Directory containing per-line HuMo
                                clips named `<line_id>.mp4`. Output
                                of OTR_BatchHumoRender.
    ledger_json         STRING  Production Ledger -- either inline
                                JSON or a path to *_ledger.json.
                                Used to walk lines in beat order
                                and compute per-clip overlay
                                windows.
    blend_mode          CHOICE  Composite blend mode for proc gen
                                on top: addition / screen / lighten
                                / overlay / normal.
    blend_opacity       FLOAT   0.0 - 1.0, default 0.5.
    canvas_width        INT     Default 1920.
    canvas_height       INT     Default 1080.
    canvas_fps          INT     Default 25.
    humo_target_height  INT     HuMo lanczos-fit height. Default
                                1080. Width derives from HuMo's
                                native 480:832 aspect (= 624).

Outputs:
    final_mp4_path  STRING  Path to the rendered composite.
    report          STRING  Human-readable summary log.

Per-line timing source priority:
    1. ledger.lines[].dur_s (and start_s) when populated by
       SceneSequencer
    2. ffprobe each clip's actual duration (fallback: every clip we
       find on disk gets ffprobed for duration)
    3. clip_length (from BatchHumoRender) as last-resort uniform
       window
"""
from __future__ import annotations

import json
import logging
import shutil
import subprocess
import sys as _sys
import time
from pathlib import Path
from typing import Any

# Path-helper bootstrap (see ``batch_humo_render.py`` for full
# rationale). ``_otr_paths`` lives as a sibling module; this prepend
# makes it importable both via the parent ``nodes`` package
# (production) and via direct file load (test fixtures).
_NODES_DIR = Path(__file__).resolve().parent
if str(_NODES_DIR) not in _sys.path:
    _sys.path.insert(0, str(_NODES_DIR))
from _otr_paths import (  # noqa: E402
    episodes_for_obs_dir,
    otr_episodes_root,
    otr_legacy_audio_dir,
    otr_stills_dir,
)

log = logging.getLogger("OTR.video_composite")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

# BUG-LOCAL-129a: minimum byte size for the radio still PNG before we
# treat it as usable for static-segment generation. Catches 0-byte /
# truncated FLUX renders (BUG-LOCAL-121).
_MIN_RADIO_STILL_BYTES = 256

# BUG-LOCAL-129a: explicit container timebase for static segments
# generated by ffmpeg. HuMo clips ship with whatever timebase ffmpeg
# picked at save time (typically tbn=12800 for libx264 mp4). Force
# the same on static segments so the concat-demuxer pass downstream
# can `-c copy` without timestamp drift at the seam (Jeffrey's review
# Q3 catch, 2026-05-01).
_STATIC_SEGMENT_TIMEBASE = "12800"


def _resolve_radio_still_for_static(ledger: dict | None) -> Path | None:
    """Resolve the radio bookend PNG path for static-segment fallback.

    Mirrors the resolution order in
    ``batch_humo_render._resolve_radio_still_path`` so VideoComposite
    and BatchHumoRender stay in lockstep:

      1. ``ledger.radio_bookend_path`` (top-level)
      2. ``ledger.meta.radio_bookend_path``
      3. Filesystem fallback at
         ``output/otr/stills/radio_bookend_<episode_id>.png``

    Returns ``Path`` if a usable PNG exists (file present, size >=
    :data:`_MIN_RADIO_STILL_BYTES`), else ``None``. Hostile-input safe.
    """
    if not isinstance(ledger, dict):
        return None

    def _is_valid(p: Path) -> bool:
        try:
            if not p.is_file():
                return False
            return p.stat().st_size >= _MIN_RADIO_STILL_BYTES
        except Exception:  # noqa: BLE001
            return False

    cand = ledger.get("radio_bookend_path")
    if not cand:
        meta = ledger.get("meta") or {}
        if isinstance(meta, dict):
            cand = meta.get("radio_bookend_path")
    if cand:
        try:
            p = Path(cand)
        except Exception:  # noqa: BLE001
            p = None
        if p is not None and _is_valid(p):
            return p
        if p is not None:
            log.warning(
                "[VideoComposite/static] ledger radio_bookend_path=%s does "
                "not exist or is truncated; trying filesystem fallback",
                p,
            )

    eid_raw = ledger.get("episode_id")
    if not isinstance(eid_raw, str):
        return None
    eid = eid_raw.strip()
    if not eid or any(t in eid for t in ("/", "\\", "..", "\x00")):
        return None
    try:
        fs_path = otr_stills_dir(eid) / f"radio_bookend_{eid}.png"
    except Exception as exc:  # noqa: BLE001
        log.warning(
            "[VideoComposite/static] otr_stills_dir(%r) lookup failed: %s",
            eid, exc,
        )
        return None
    if _is_valid(fs_path):
        log.info(
            "[VideoComposite/static] radio still resolved via filesystem "
            "fallback: %s",
            fs_path,
        )
        return fs_path
    return None


def _render_static_radio_segment(
    *,
    radio_png: Path,
    dur_s: float,
    canvas_w: int,
    canvas_h: int,
    canvas_fps: int,
    out_path: Path,
    ffmpeg: str,
) -> Path:
    """BUG-LOCAL-129a: generate a deterministic static video segment
    from the radio bookend PNG, sized to the canvas dims, no audio,
    exact frame count, fixed timebase.

    Used to fill ledger lines that have no corresponding HuMo clip
    on disk (announcer / music_* / sfx in the post-BUG-129b world,
    or any line where BatchHumoRender failed to render a clip).

    Strict invariants (each catches a different Jeffrey-review gotcha):
      - ``-frames:v <int(round(dur_s * canvas_fps))>`` -- exact frame
        count, NOT ``-t``. Round-to-frame at generation time so
        cumulative drift across many static segments is bounded to
        +/- 0.5 frame at each seam, not accumulating.
      - ``-r <canvas_fps>`` -- output fps locked to canvas fps (must
        match HuMo's ``HUMO_FPS = 25`` exactly to avoid concat-demuxer
        frame-rate mismatch).
      - ``-video_track_timescale 12800`` -- match HuMo clip container
        timebase so concat-demuxer with ``-c copy`` produces a clean
        timestamp stream.
      - ``-an`` -- no audio. Master mix attaches in the final mux
        step, same as for HuMo clips.
      - libx264 yuv420p crf=18 preset=fast -- match the pillarbox
        re-encode profile so concat-demuxer with ``-c copy`` doesn't
        reject the stream.
      - scale + pad to canvas_w x canvas_h with center alignment so
        the still fills the canvas without distortion regardless of
        the source PNG aspect ratio.
    """
    frame_count = max(1, int(round(float(dur_s) * float(canvas_fps))))
    out_path.parent.mkdir(parents=True, exist_ok=True)
    # scale to fit-inside canvas, then pad to canvas dims (center).
    vf = (
        f"scale={canvas_w}:{canvas_h}:force_original_aspect_ratio=decrease,"
        f"pad={canvas_w}:{canvas_h}:(ow-iw)/2:(oh-ih)/2:color=black,"
        f"format=yuv420p"
    )
    cmd = [
        ffmpeg, "-y", "-loglevel", "error",
        "-loop", "1",
        "-i", str(radio_png),
        "-vf", vf,
        "-r", str(int(canvas_fps)),
        "-frames:v", str(frame_count),
        "-c:v", "libx264", "-pix_fmt", "yuv420p",
        "-crf", "18", "-preset", "fast",
        "-video_track_timescale", _STATIC_SEGMENT_TIMEBASE,
        "-an",
        str(out_path),
    ]
    subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    return out_path


def _ffprobe_dur(path: Path, ffprobe: str = "ffprobe") -> float | None:
    """Return mp4 duration in seconds, or None on failure."""
    try:
        r = subprocess.run(
            [ffprobe, "-v", "error",
             "-show_entries", "format=duration",
             "-of", "default=noprint_wrappers=1:nokey=1",
             str(path)],
            capture_output=True, text=True, check=True,
        )
        return float(r.stdout.strip())
    except Exception as exc:
        log.warning("[VideoComposite] ffprobe %s failed: %s", path, exc)
        return None


def _load_ledger(arg: str) -> dict:
    """Backwards-compat shim around _load_ledger_with_path. Returns
    only the parsed ledger dict for callers that don't need the
    source path. New code should prefer _load_ledger_with_path so
    the source path is available for write-back."""
    ledger, _ = _load_ledger_with_path(arg)
    return ledger


def _load_ledger_with_path(arg: str) -> tuple[dict, "Path | None"]:
    """Accept inline JSON, ledger.json path, .mp4 path (suffix-swap
    to ledger), or empty (auto-pick newest non-pending). Mirrors
    BatchHumoRender._load_ledger_with_path so wiring is consistent.

    Returns (ledger_dict, ledger_path_or_None). Path is None for
    inline JSON; BUG-LOCAL-089 final_video_path write-back skips
    in that case rather than synthesizing a new file.
    """
    s = (arg or "").strip()

    if not s:
        audio_dirs = [
            otr_episodes_root(),
            otr_legacy_audio_dir(),
        ]
        cands = []
        for d in audio_dirs:
            if d.exists():
                cands.extend(
                    p for p in d.glob("*_ledger.json")
                    if not p.name.startswith("pending_")
                )
        if not cands:
            raise RuntimeError("VideoComposite: ledger_json empty and auto-pick found no ledger")
        p = max(cands, key=lambda x: x.stat().st_mtime)
        with open(p, "r", encoding="utf-8") as f:
            return json.load(f), p

    if s.startswith("{"):
        return json.loads(s), None

    p = Path(s)
    # .mp4 path -> swap suffix to _ledger.json (SignalLostVideo convention)
    if p.suffix.lower() == ".mp4":
        ledger_p = p.with_suffix("").parent / f"{p.stem}_ledger.json"
        if ledger_p.exists():
            with open(ledger_p, "r", encoding="utf-8") as f:
                return json.load(f), ledger_p
        raise RuntimeError(
            f"VideoComposite: derived ledger from .mp4 not found: {ledger_p}"
        )

    if not p.exists():
        raise RuntimeError(f"VideoComposite: ledger path not found: {p}")
    with open(p, "r", encoding="utf-8") as f:
        return json.load(f), p


def _build_clip_timeline(
    ledger: dict,
    clips_dir: Path,
    fallback_clip_length: float,
    ffprobe: str = "ffprobe",
) -> list[tuple[Path, float, float]]:
    """Build [(clip_path, start_s, dur_s), ...] for every ledger line
    that has a clip on disk. Cumulative start_s across the timeline
    -- ignores ledger.start_s except as a hint (we trust the actual
    rendered clip duration over ledger arithmetic)."""
    lines = ledger.get("lines") or []
    timeline: list[tuple[Path, float, float]] = []
    cumulative = 0.0
    for ln in lines:
        line_id = str(ln.get("line_id") or "")
        if not line_id:
            continue
        clip_path = clips_dir / f"{line_id}.mp4"
        if not clip_path.exists():
            log.info("[VideoComposite] line %s: clip not on disk, skipping", line_id)
            continue
        # Prefer ledger dur_s if positive, else ffprobe, else fallback
        dur = ln.get("dur_s")
        if dur is None or float(dur) <= 0:
            dur = _ffprobe_dur(clip_path, ffprobe)
        if dur is None or float(dur) <= 0:
            dur = float(fallback_clip_length)
        timeline.append((clip_path, cumulative, float(dur)))
        cumulative += float(dur)
    return timeline


def _build_filter_graph(
    procgen_video: Path,
    timeline: list[tuple[Path, float, float]],
    canvas_w: int,
    canvas_h: int,
    canvas_fps: int,
    humo_h: int,
    blend_mode: str,
    blend_opacity: float,
    episode_dur: float,
) -> tuple[str, list[Path]]:
    """Build the ffmpeg -filter_complex string + ordered input list.

    Inputs (0-indexed):
        [0]  procgen video (base layer + audio source)
        [1..N] HuMo clips, one per timeline entry

    Filter graph (BUG-LOCAL-092 architecture):
        [0:v] fps -> scale -> setsar -> [procgen]
        [i:v] fps -> scale 624:humo_h -> setsar ->
              setpts (per-clip start_s) -> [hi]
        chain: [procgen] overlay each [hi] at x=offset_x,y=0 with
               enable='between(t,start,start+dur)'
        (optional) blend pass for `additive procgen-over-humo`
                    feel -- lower default opacity, screen mode by
                    default; opacity=0 disables the pass entirely.
        final: [...] -> [v]

    Why this order: procgen is the BASE (full opacity), HuMo
    overlays opaquely at the center pillarbox during each line's
    time window. The pillarbox sides ALWAYS show full procgen
    (the audio-reactive CRT visualizer Jeffrey wants), and the
    center swaps to HuMo only while a character is speaking.
    The previous order (black canvas + HuMo on top + blanket-
    blend procgen at addition@0.5) drowned everything in the
    procgen color cast (BUG-LOCAL-092 magenta/pink wash).
    """
    humo_w = round(humo_h * (480 / 832) / 8) * 8  # snap to mult of 8 (h264 chroma safe)
    offset_x = (canvas_w - humo_w) // 2

    parts = []
    # [0] procgen → time-aligned + scaled = BASE layer (sides + initial center)
    parts.append(
        f"[0:v]fps={canvas_fps},scale={canvas_w}:{canvas_h},setsar=1[procgen]"
    )
    # Per-clip scale + overlay chain. HuMo overlays directly on procgen.
    last_label = "procgen"
    inputs_list: list[Path] = [procgen_video]
    for idx, (clip_path, start_s, dur_s) in enumerate(timeline):
        in_idx = idx + 1
        inputs_list.append(clip_path)
        parts.append(
            f"[{in_idx}:v]fps={canvas_fps},scale={humo_w}:{humo_h},setsar=1,"
            f"setpts=PTS-STARTPTS+{start_s:.3f}/TB[h{idx}]"
        )
        new_label = f"s{idx}"
        end_s = start_s + dur_s
        parts.append(
            f"[{last_label}][h{idx}]overlay=x={offset_x}:y=0:"
            f"enable='between(t,{start_s:.3f},{end_s:.3f})'[{new_label}]"
        )
        last_label = new_label

    # Optional subtle procgen-over-HuMo "audio-reactive sheen" pass.
    # opacity=0 disables it entirely. Default is now low (0.0 in
    # widgets) so the composite is clean by default; users who want
    # the additive sheen can dial up blend_opacity in the widget.
    if blend_opacity and blend_opacity > 0:
        parts.append(
            f"[{last_label}][procgen]blend=all_mode={blend_mode}:"
            f"all_opacity={blend_opacity:.3f}[v]"
        )
    else:
        # Just rename the last overlay output to [v]
        parts.append(f"[{last_label}]copy[v]")
    return ";".join(parts), inputs_list


# ---------------------------------------------------------------------------
# humo_concat mode helpers (audio_source = "humo_concat")
# ---------------------------------------------------------------------------

def _make_gap_segment(
    image: Path,
    audio_source: Path,
    start_s: float,
    end_s: float,
    canvas_w: int,
    canvas_h: int,
    canvas_fps: int,
    out_path: Path,
    ffmpeg: str,
) -> Path:
    """Render a static-image mp4 covering [start_s, end_s] of the
    timeline. Image is letterboxed to canvas dimensions; audio is
    sliced from `audio_source` (typically the procgen mp4 carrying
    the master_mix track).

    Used to fill gap windows between HuMo dialogue clips in the
    humo_concat mode so the timeline has full visual + audio
    coverage. Falls back to silence if audio_source missing.
    """
    dur = max(0.0, end_s - start_s)
    if dur <= 0.0:
        raise ValueError(f"_make_gap_segment: non-positive duration {dur}")
    cmd = [
        ffmpeg, "-y", "-loglevel", "error",
        "-loop", "1", "-framerate", str(canvas_fps), "-i", str(image),
        "-ss", f"{start_s:.4f}", "-i", str(audio_source),
        "-vf", (
            f"scale={canvas_w}:{canvas_h}:force_original_aspect_ratio=decrease,"
            f"pad={canvas_w}:{canvas_h}:(ow-iw)/2:(oh-ih)/2:color=black,"
            f"fps={canvas_fps}"
        ),
        "-t", f"{dur:.4f}",
        "-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "18", "-preset", "fast",
        "-c:a", "aac", "-b:a", "192k", "-ar", "48000",
        "-shortest",
        str(out_path),
    ]
    subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    return out_path


def _normalize_humo_segment(
    clip: Path,
    canvas_w: int,
    canvas_h: int,
    canvas_fps: int,
    humo_target_h: int,
    out_path: Path,
    ffmpeg: str,
) -> Path:
    """Pillarbox a HuMo clip into the canvas dimensions while
    PRESERVING its native audio (the source of mechanical lip-sync
    for the humo_concat mode). HuMo clips are 480x832 portrait;
    pillarbox to canvas_w x canvas_h with black side bars.
    """
    cmd = [
        ffmpeg, "-y", "-loglevel", "error",
        "-i", str(clip),
        "-vf", (
            f"scale=-2:{humo_target_h}:force_original_aspect_ratio=decrease,"
            f"pad={canvas_w}:{canvas_h}:(ow-iw)/2:(oh-ih)/2:color=black,"
            f"fps={canvas_fps}"
        ),
        "-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "18", "-preset", "fast",
        # KEY: keep HuMo's native audio for perfect lip-sync.
        "-c:a", "aac", "-b:a", "192k", "-ar", "48000",
        str(out_path),
    ]
    subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    return out_path


def _resolve_bookend_image(
    ledger: dict,
    procgen: Path,
    fallback_dir: Path,
    ffmpeg: str,
) -> Path:
    """Locate the radio bookend image. Priority:
    1. ledger.radio_bookend_path (top-level field stamped by BatchFluxRender)
    2. ledger.meta.radio_bookend_path
    3. Fallback: extract first frame from procgen mp4
    """
    cand = ledger.get("radio_bookend_path") or ledger.get("meta", {}).get("radio_bookend_path")
    if cand:
        p = Path(cand)
        if p.exists():
            return p
        log.warning(
            "[VideoComposite] ledger.radio_bookend_path=%s does not exist; "
            "falling back to procgen frame",
            p,
        )
    fallback = fallback_dir / "bookend_fallback.png"
    if not fallback.exists():
        cmd = [
            ffmpeg, "-y", "-loglevel", "error",
            "-i", str(procgen), "-vframes", "1",
            str(fallback),
        ]
        subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        log.info("[VideoComposite] bookend fallback: extracted %s", fallback)
    return fallback


def _pillarbox_humo_silent(
    clip: Path,
    canvas_w: int,
    canvas_h: int,
    canvas_fps: int,
    humo_target_h: int,
    out_path: Path,
    ffmpeg: str,
    extend_tail_s: float = 0.0,
) -> Path:
    """Pillarbox a HuMo clip into the canvas dimensions and STRIP
    its audio entirely (-an).  Video re-encodes via libx264; audio
    is dropped so the downstream mux step can attach the master mix
    audio with `-c:a copy` (no audio re-encode anywhere).

    Used by the master_mix_per_clip_mux mode (Step 6 of ROADMAP P0,
    2026-04-30 lock).  The whole point of this helper vs.
    `_normalize_humo_segment` is that this one drops the audio so
    the C7 byte-perfect path doesn't contaminate the master mix
    with a re-encoded HuMo native audio it'll discard anyway.

    ``extend_tail_s`` (2026-04-30 round-robin hardening, applied to
    the LAST clip in the timeline only): freeze-extend the final
    frame for this many seconds via ffmpeg's tpad filter.  This
    guarantees the silent_combined.mp4 ends slightly LATER than the
    master mix audio so the mux step's `-shortest` truncates an
    inaudible video tail rather than the trailing audio.  Without
    this, video frame quantization (40ms at 25fps) plus chunk
    rounding error can leave silent_combined a few frames short of
    the master mix duration -- and `-shortest` would then nuke the
    end of the audio, breaking C7 silently.  Adds zero re-encodes
    (tpad piggybacks the libx264 pass already happening here).
    """
    vf = (
        f"scale=-2:{humo_target_h}:force_original_aspect_ratio=decrease,"
        f"pad={canvas_w}:{canvas_h}:(ow-iw)/2:(oh-ih)/2:color=black,"
        f"fps={canvas_fps}"
    )
    if extend_tail_s > 0.0:
        # tpad with stop_mode=clone replays the last frame; cleaner
        # than introducing a second re-encode pass.  Append to the
        # filter chain so it runs after pillarbox.
        vf = f"{vf},tpad=stop_mode=clone:stop_duration={extend_tail_s:.3f}"
    cmd = [
        ffmpeg, "-y", "-loglevel", "error",
        "-i", str(clip),
        "-vf", vf,
        "-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "18", "-preset", "fast",
        "-an",  # KEY: strip audio.  Master mix attaches at mux step.
        str(out_path),
    ]
    subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    return out_path


def _render_master_mix_per_clip_mux_mode(
    *,
    ledger: dict,
    clips_dir: Path,
    procgen: Path,
    out_mp4: Path,
    canvas_w: int,
    canvas_h: int,
    canvas_fps: int,
    humo_target_h: int,
    fallback_clip_length: float,
    ffmpeg: str,
    ffprobe: str,
) -> tuple[Path, list[str]]:
    """C7-byte-perfect mode (Step 6 of ROADMAP P0, 2026-04-30 lock).

    Pipeline:
      1. Sort ledger.lines[] by start_s; resolve each line's HuMo
         silent video on disk (clips_dir/<line_id>.mp4).
      2. For each line, pillarbox the HuMo clip to canvas dims with
         ``-an`` (strip audio).  Video gets one libx264 re-encode;
         audio is dropped entirely so it can't contaminate the
         master mix that attaches at step 4.
      3. concat-demuxer the pillarboxed silent clips with ``-c copy``
         (no video re-encode, no audio at all yet).
      4. Mux the silent combined video with the procgen master mix
         audio (single ffmpeg call, ``-c:v copy -c:a copy
         -shortest``).  Audio passes through with ZERO re-encodes.

    Total audio encodes vs. the existing ``humo_concat`` path:
      humo_concat: 3 ^^ AAC re-encodes (gap_segment + per-clip
                   normalize + final concat, lines 318/350/522).
      this mode:   0 audio re-encodes downstream of
                   SignalLostVideo's CreateVideo step.

    Returns (final_mp4_path, report_lines).  Raises on any
    unrecoverable subprocess failure so the caller can fall back to
    the legacy mode.

    Crossfade overlap regions (~500ms) between music_open and the
    first scene line, and the last scene line + music_close, are
    NOT crossfaded visually here -- the final concat is a hard cut.
    Adding a video crossfade would require re-encoding.  For
    SIGNAL LOST aesthetic, hard cuts on broadcast-distress
    transitions are acceptable; promote to filter-based crossfade
    if a future revision wants smoother seams.
    """
    report: list[str] = []
    t0 = time.time()

    # 1. Build timeline from ledger.lines[] (Step 4b/4c populated
    # speaker_role + start_s + dur_s for ALL audio events: dialogue,
    # announcer, sfx, music_open, music_close).  Walk lines instead
    # of clips so we honour the unified-coverage contract.
    #
    # BUG-LOCAL-129a (2026-05-01): when a line has no HuMo clip on
    # disk, fall back to a deterministic static-radio-still segment
    # rather than silently skipping. Closes the per-line audio/video
    # coverage gap that BUG-LOCAL-128 surfaced (sum(clip.dur_s) <
    # sum(line.dur_s) when HuMo can't / shouldn't render a line, e.g.
    # post-BUG-129b when announcer/music/sfx stop dispatching to HuMo
    # entirely). Still skips silently if no radio still is available.
    ledger_lines = ledger.get("lines") or []
    static_radio_png = _resolve_radio_still_for_static(ledger)
    static_seg_dir = out_mp4.parent / "_per_clip_mux_segments"
    timeline: list[dict] = []
    for ln in ledger_lines:
        line_id = str(ln.get("line_id") or "")
        if not line_id:
            continue
        start_s = ln.get("start_s")
        dur_s = ln.get("dur_s")
        if not isinstance(start_s, (int, float)) or not isinstance(dur_s, (int, float)):
            continue
        if dur_s <= 0:
            continue
        speaker_role = ln.get("speaker_role") or "character"
        clip_path = clips_dir / f"{line_id}.mp4"
        if clip_path.is_file():
            timeline.append({
                "line_id": line_id,
                "start_s": float(start_s),
                "dur_s": float(dur_s),
                "clip_path": clip_path,
                "speaker_role": speaker_role,
                "source_kind": "humo",
            })
            continue
        # Missing HuMo clip. Try static-radio fallback (BUG-129a).
        if static_radio_png is None:
            log.info(
                "[VideoComposite/per_clip_mux] skip %s: clip not on disk "
                "and no radio still available "
                "(speaker_role=%s start_s=%.3f dur_s=%.3f)",
                line_id, speaker_role, float(start_s), float(dur_s),
            )
            continue
        try:
            static_out = static_seg_dir / f"static_{line_id}.mp4"
            _render_static_radio_segment(
                radio_png=static_radio_png,
                dur_s=float(dur_s),
                canvas_w=canvas_w,
                canvas_h=canvas_h,
                canvas_fps=canvas_fps,
                out_path=static_out,
                ffmpeg=ffmpeg,
            )
        except subprocess.CalledProcessError as exc:
            stderr = exc.stderr.decode("utf-8", errors="replace") if exc.stderr else ""
            log.warning(
                "[VideoComposite/per_clip_mux] static-radio fallback for "
                "%s FAILED, skipping line: %s",
                line_id, stderr[:200],
            )
            continue
        log.info(
            "[VideoComposite/per_clip_mux] static-radio fill for %s "
            "(speaker_role=%s start_s=%.3f dur_s=%.3f) -> %s",
            line_id, speaker_role,
            float(start_s), float(dur_s), static_out.name,
        )
        timeline.append({
            "line_id": line_id,
            "start_s": float(start_s),
            "dur_s": float(dur_s),
            "clip_path": static_out,
            "speaker_role": speaker_role,
            "source_kind": "static_ffmpeg",
        })

    if not timeline:
        raise RuntimeError(
            "per_clip_mux: no usable HuMo clips for any line in "
            "ledger.lines[] (Step 6 requires Step 4b/4c-stamped roles "
            "and BatchHumoRender output for every audio event)"
        )

    timeline.sort(key=lambda x: x["start_s"])
    n_humo = sum(1 for e in timeline if e.get("source_kind") == "humo")
    n_static = sum(1 for e in timeline if e.get("source_kind") == "static_ffmpeg")
    report.append(
        f"per_clip_mux: timeline = {len(timeline)} clip(s) "
        f"({sum(1 for e in timeline if e['speaker_role']=='character')} char + "
        f"{sum(1 for e in timeline if e['speaker_role']=='announcer')} announcer + "
        f"{sum(1 for e in timeline if e['speaker_role']=='sfx')} sfx + "
        f"{sum(1 for e in timeline if e['speaker_role'] in ('music_open','music_close','music_inter'))} music) "
        f"[{n_humo} humo + {n_static} static]"
    )

    # 2. Pillarbox each HuMo clip to canvas dims and strip audio.
    # 2026-04-30 round-robin hardening: freeze-extend the surviving
    # LAST clip by 500 ms so silent_combined ends after the master
    # mix audio, so the mux step's `-shortest` truncates an inaudible
    # video tail rather than the trailing audio. Cumulative chunk-
    # rounding error across many clips can otherwise leave
    # silent_combined a few frames short, silently breaking C7 at
    # episode end.
    #
    # BUG-LOCAL-128 fix (2026-05-01): the previous policy padded
    # `idx == last_idx` where `last_idx = len(timeline) - 1` was
    # computed BEFORE the loop. If that clip failed pillarbox, the
    # surviving last clip got no tail pad and `-shortest` truncated
    # trailing audio. New policy: don't pad in the loop; re-pillarbox
    # the actual `pillarboxed[-1]` with tail pad after the loop. One
    # extra ffmpeg call when everything succeeds, correct behaviour
    # when the original last clip fails.
    _TAIL_PAD_S = 0.5
    seg_dir = out_mp4.parent / "_per_clip_mux_segments"
    seg_dir.mkdir(parents=True, exist_ok=True)
    pillarboxed: list[Path] = []
    pb_failures = 0
    for entry in timeline:
        seg_out = seg_dir / f"pb_{entry['line_id']}.mp4"
        try:
            _pillarbox_humo_silent(
                clip=entry["clip_path"],
                canvas_w=canvas_w, canvas_h=canvas_h,
                canvas_fps=canvas_fps, humo_target_h=humo_target_h,
                out_path=seg_out, ffmpeg=ffmpeg,
                extend_tail_s=0.0,
            )
            pillarboxed.append(seg_out)
        except subprocess.CalledProcessError as exc:
            stderr = exc.stderr.decode("utf-8", errors="replace") if exc.stderr else ""
            log.warning(
                "[VideoComposite/per_clip_mux] pillarbox %s failed: %s",
                entry["line_id"], stderr[:200],
            )
            report.append(
                f"  pillarbox {entry['line_id']}: FAILED ({stderr[:120]})"
            )
            pb_failures += 1

    if not pillarboxed:
        raise RuntimeError(
            "per_clip_mux: no segments survived pillarbox pass "
            "(check ffmpeg invocations + HuMo clip integrity)"
        )
    if pb_failures:
        report.append(
            f"per_clip_mux: WARNING {pb_failures} clip(s) lost during "
            f"pillarbox pass; proceeding with {len(pillarboxed)} survivors"
        )

    # 2b. BUG-LOCAL-128 fix: re-pillarbox the ACTUAL surviving last
    # clip with tail pad. Locate the timeline entry whose line_id
    # matches `pillarboxed[-1].stem` (stripped of "pb_" prefix), then
    # call _pillarbox_humo_silent again with extend_tail_s set. If
    # the re-pad call itself fails, log loudly and continue without
    # the pad -- the user gets a clear signal in the report and audio
    # may be tail-truncated but everything else still ships.
    surviving_last = pillarboxed[-1]
    surviving_line_id = surviving_last.stem
    if surviving_line_id.startswith("pb_"):
        surviving_line_id = surviving_line_id[3:]
    surviving_entry = next(
        (e for e in timeline if e["line_id"] == surviving_line_id),
        None,
    )
    if surviving_entry is None:
        log.warning(
            "[VideoComposite/per_clip_mux] could not locate timeline "
            "entry for surviving last clip %s; skipping tail pad",
            surviving_line_id,
        )
        report.append(
            f"  tail-pad: SKIPPED (no timeline match for {surviving_line_id})"
        )
    else:
        try:
            _pillarbox_humo_silent(
                clip=surviving_entry["clip_path"],
                canvas_w=canvas_w, canvas_h=canvas_h,
                canvas_fps=canvas_fps, humo_target_h=humo_target_h,
                out_path=surviving_last, ffmpeg=ffmpeg,
                extend_tail_s=_TAIL_PAD_S,
            )
            report.append(
                f"  tail-pad: +{_TAIL_PAD_S:.3f}s on {surviving_line_id} "
                f"(BUG-LOCAL-128 fix)"
            )
            log.info(
                "[VideoComposite/per_clip_mux] tail-pad +%.3fs on actual "
                "surviving last clip %s (BUG-LOCAL-128 fix)",
                _TAIL_PAD_S, surviving_line_id,
            )
        except subprocess.CalledProcessError as exc:
            stderr = exc.stderr.decode("utf-8", errors="replace") if exc.stderr else ""
            log.warning(
                "[VideoComposite/per_clip_mux] tail-pad on %s FAILED; "
                "trailing audio may be truncated by -shortest: %s",
                surviving_line_id, stderr[:200],
            )
            report.append(
                f"  tail-pad: FAILED on {surviving_line_id} "
                f"({stderr[:120]}) -- audio may truncate"
            )

    # 3. concat-demuxer the silent pillarboxed clips with -c copy.
    list_file = seg_dir / "concat.txt"
    list_file.write_text(
        "\n".join(f"file '{s.as_posix()}'" for s in pillarboxed),
        encoding="utf-8",
    )
    silent_combined = seg_dir / "silent_combined.mp4"
    cmd = [
        ffmpeg, "-y", "-loglevel", "warning",
        "-f", "concat", "-safe", "0",
        "-i", str(list_file),
        "-c", "copy",   # NO re-encode -- pillarbox already produced
                        # uniform H.264 yuv420p at canvas dims.
        str(silent_combined),
    ]
    subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    report.append(
        f"per_clip_mux: concat OK -> silent_combined {silent_combined.name}"
    )

    # 4. Mux silent_combined video + procgen master-mix audio with
    # -c copy throughout.  This is the C7-critical step: audio
    # passes through without re-encode.  -shortest trims any audio
    # overhang past the combined video length.
    cmd = [
        ffmpeg, "-y", "-loglevel", "warning",
        "-i", str(silent_combined),
        "-i", str(procgen),
        "-map", "0:v",   # video from concatenated HuMo
        "-map", "1:a",   # audio from procgen master mix
        "-c:v", "copy",
        "-c:a", "copy",
        "-shortest",
        str(out_mp4),
    ]
    subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

    elapsed = time.time() - t0
    report.append(
        f"per_clip_mux: assembled {out_mp4.name} in {elapsed:.1f}s "
        f"(audio passthrough, 0 re-encodes downstream of SignalLostVideo)"
    )
    return out_mp4, report


def _render_humo_concat_mode(
    *,
    ledger: dict,
    clips_dir: Path,
    procgen: Path,
    out_mp4: Path,
    canvas_w: int,
    canvas_h: int,
    canvas_fps: int,
    humo_target_h: int,
    fallback_clip_length: float,
    ffmpeg: str,
    ffprobe: str,
) -> tuple[Path, list[str]]:
    """Build the final mp4 in humo_concat mode.

    Pipeline:
      1. Sort ledger.clips[] by start_s, build (clip_path, start_s, dur_s)
         tuples honouring REAL master-mix timestamps (not cumulative).
      2. Resolve radio bookend image (or procgen-frame fallback).
      3. For each pair of adjacent clips with a gap between them,
         create a gap segment: bookend image + master_mix audio slice.
      4. For each HuMo clip, normalize to canvas dims keeping native
         audio (mechanical lip-sync guarantee).
      5. ffmpeg concat-demuxer joins all segments in time order.

    Returns (final_mp4_path, report_lines).
    """
    report: list[str] = []
    t0 = time.time()

    # 1. Build timeline from ledger.clips[] using real master-mix start_s
    ledger_clips = ledger.get("clips") or []
    timeline: list[tuple[Path, float, float]] = []
    for entry in ledger_clips:
        line_id = str(entry.get("line_id") or "")
        if not line_id:
            continue
        cp = Path(entry.get("mp4_path") or "")
        if not cp.exists():
            cp = clips_dir / f"{line_id}.mp4"
        if not cp.exists():
            log.info(
                "[VideoComposite/humo_concat] skip %s: clip not on disk",
                line_id,
            )
            continue
        start_s = float(entry.get("start_s") or 0.0)
        dur_s = float(entry.get("dur_s") or 0.0)
        if dur_s <= 0:
            dur_s = _ffprobe_dur(cp, ffprobe) or float(fallback_clip_length)
        timeline.append((cp, start_s, dur_s))
    if not timeline:
        raise RuntimeError("humo_concat: no usable HuMo clips in ledger.clips[]")
    timeline.sort(key=lambda t: t[1])

    # 2. Episode duration (from procgen so we cover trailing music)
    episode_dur = _ffprobe_dur(procgen, ffprobe) or (timeline[-1][1] + timeline[-1][2])
    report.append(
        f"humo_concat: {len(timeline)} HuMo clip(s), episode duration "
        f"{episode_dur:.2f}s"
    )

    # 3. Resolve bookend image
    seg_dir = out_mp4.parent / "_humo_concat_segments"
    seg_dir.mkdir(parents=True, exist_ok=True)
    bookend = _resolve_bookend_image(ledger, procgen, seg_dir, ffmpeg)
    report.append(f"humo_concat: bookend image = {bookend.name}")

    # 4. Build segment list (alternating gap, clip, gap, ...)
    segments: list[Path] = []
    cursor = 0.0
    for i, (clip_path, start_s, dur_s) in enumerate(timeline):
        if start_s - cursor > 0.05:  # 50ms tolerance for float drift
            gap_path = seg_dir / f"gap_{i:03d}.mp4"
            try:
                _make_gap_segment(
                    bookend, procgen, cursor, start_s,
                    canvas_w, canvas_h, canvas_fps,
                    gap_path, ffmpeg,
                )
                segments.append(gap_path)
            except Exception as exc:
                log.warning(
                    "[VideoComposite/humo_concat] gap[%d, %.2f-%.2f] failed: %s",
                    i, cursor, start_s, exc,
                )
        clip_seg = seg_dir / f"clip_{i:03d}.mp4"
        try:
            _normalize_humo_segment(
                clip_path, canvas_w, canvas_h, canvas_fps,
                humo_target_h, clip_seg, ffmpeg,
            )
            segments.append(clip_seg)
        except Exception as exc:
            log.warning(
                "[VideoComposite/humo_concat] clip[%d] %s normalize failed: %s",
                i, clip_path.name, exc,
            )
            continue
        cursor = start_s + dur_s
    # Trailing gap
    if cursor < episode_dur - 0.05:
        try:
            tail_seg = seg_dir / "gap_999.mp4"
            _make_gap_segment(
                bookend, procgen, cursor, episode_dur,
                canvas_w, canvas_h, canvas_fps,
                tail_seg, ffmpeg,
            )
            segments.append(tail_seg)
        except Exception as exc:
            log.warning(
                "[VideoComposite/humo_concat] trailing gap %.2f-%.2f failed: %s",
                cursor, episode_dur, exc,
            )

    if not segments:
        raise RuntimeError("humo_concat: no segments produced")
    report.append(f"humo_concat: {len(segments)} segment(s) ready for concat")

    # 5. Concat-demuxer assembly
    list_file = seg_dir / "concat.txt"
    list_file.write_text(
        "\n".join(f"file '{s.as_posix()}'" for s in segments),
        encoding="utf-8",
    )
    cmd = [
        ffmpeg, "-y", "-loglevel", "warning",
        "-f", "concat", "-safe", "0",
        "-i", str(list_file),
        "-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "18", "-preset", "fast",
        "-c:a", "aac", "-b:a", "192k", "-ar", "48000",
        str(out_mp4),
    ]
    subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    elapsed = time.time() - t0
    report.append(
        f"humo_concat: assembled {out_mp4.name} in {elapsed:.1f}s"
    )
    return out_mp4, report


# ---------------------------------------------------------------------------
# Node class
# ---------------------------------------------------------------------------

class VideoComposite:
    """Compose proc gen base + N HuMo clips into a final 1920x1080 mp4."""

    CATEGORY = "OTR/v2/Visual"
    FUNCTION = "execute"
    RETURN_TYPES = ("STRING", "STRING")
    RETURN_NAMES = ("final_mp4_path", "report")
    OUTPUT_NODE = True

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "procgen_video_path": ("STRING", {
                    "multiline": False,
                    "default": "",
                    "tooltip": (
                        "Path to OTR_SignalLostVideo's mp4 output "
                        "(audio-reactive CRT base, full-episode audio)."
                    ),
                }),
                "clips_dir": ("STRING", {
                    "multiline": False,
                    "default": "",
                    "tooltip": (
                        "Directory of per-line HuMo clips "
                        "(<line_id>.mp4). Output of "
                        "OTR_BatchHumoRender."
                    ),
                }),
                "ledger_json": ("STRING", {
                    "multiline": True,
                    "default": "",
                    "tooltip": (
                        "Ledger source. Three accepted forms "
                        "(duck-typed at _load_ledger_with_path in "
                        "nodes/batch_humo_render.py lines 1660-1762):\n"
                        "  1. Empty string -> auto-pick newest "
                        "non-pending ledger from disk.\n"
                        "  2. String starting with '{' -> parsed as "
                        "JSON manifest directly.\n"
                        "  3. Filesystem path -> if .mp4, multi-tier "
                        "stem fallback to *_ledger.json (intentional; "
                        "static analyzers regularly misflag this as a "
                        "wiring error -- see BUG-124 revert).\n"
                        "Slot name kept as 'ledger_json' for workflow "
                        "compat; rename would orphan existing wires "
                        "(no ComfyUI input aliasing)."
                    ),
                }),
            },
            "optional": {
                # BUG-LOCAL-092: defaults flipped.
                # Old defaults (addition @ 0.5) blanket-drowned the
                # composite in procgen color cast (Jeffrey's "horrendously
                # pink" feedback). New defaults: `lighten` mode, opacity
                # 0.0 (sheen pass disabled by default). User can dial
                # opacity up for the audio-reactive sheen flash; lighten
                # mode preserves HuMo skin tones since it only takes the
                # max(procgen, humo) per channel rather than additively
                # tinting.
                "blend_mode": (
                    ["lighten", "screen", "addition", "overlay", "normal"],
                    {"default": "lighten"},
                ),
                "blend_opacity": ("FLOAT", {
                    "default": 0.0, "min": 0.0, "max": 1.0, "step": 0.05,
                }),
                # 2026-05-01 EVENING (Jeffrey): downscale to NATIVE
                # render dims so the iteration cycle is fast. HuMo and
                # LTX both render at 832x480 natively; pre-this change
                # we pillarboxed up to 1920x1080 (slow per-frame
                # encode) before final mux. New default: same canvas
                # as native render, no upscale until a separate
                # upscaler stage (RTX VSR) is added later.
                "canvas_width": ("INT", {"default": 832, "min": 256, "max": 3840, "step": 8}),
                "canvas_height": ("INT", {"default": 480, "min": 256, "max": 2160, "step": 8}),
                "canvas_fps": ("INT", {"default": 25, "min": 12, "max": 60}),
                "humo_target_height": ("INT", {
                    "default": 480, "min": 256, "max": 2160, "step": 8,
                }),
                "fallback_clip_length": ("FLOAT", {
                    "default": 7.0, "min": 1.0, "max": 9.0, "step": 0.04,
                }),
                "ffmpeg": ("STRING", {
                    "default": "ffmpeg",
                    "multiline": False,
                    "tooltip": "ffmpeg binary path or name on PATH.",
                }),
                "cleanup_clips_after_assembly": ("BOOLEAN", {
                    "default": False,
                    "tooltip": (
                        "[DEFAULT OFF -- experimental] If ON, after the "
                        "final mp4 is written and verified, delete every "
                        "per-line HuMo clip mp4 listed in ledger.clips[]. "
                        "Saves disk space (33 clips x 25 MB = ~800 MB per "
                        "episode) once the per-clip files are no longer "
                        "needed for re-encoding or VideoComposite re-runs. "
                        "Each deleted clip's ledger entry gets "
                        "'cleaned_up: true' stamped so a postmortem can "
                        "tell deleted-on-purpose from missing-due-to-bug. "
                        "Recommended OFF until BUG-101/102/106 are fully "
                        "stable -- you may want to re-encode a single "
                        "clip without re-running the 5-hour HuMo render."
                    ),
                }),
                "audio_source": (
                    ["master_mix_per_clip_mux", "humo_concat", "master_mix"],
                    {"default": "master_mix_per_clip_mux",
                     "tooltip": (
                         "master_mix_per_clip_mux (DEFAULT, C7 BYTE-PERFECT): "
                         "Step 6 of the 2026-04-30 ROADMAP P0 lock. Pillarbox "
                         "each HuMo clip silent (one libx264 video re-encode), "
                         "concat-demux with -c copy, then mux procgen master "
                         "mix audio onto the silent combined video with "
                         "-c:a copy. Net audio re-encodes downstream of "
                         "SignalLostVideo: ZERO. Requires Step 4b/4c "
                         "speaker_role coverage (every audio event in "
                         "ledger.lines[]). Falls through to humo_concat on "
                         "any unrecoverable subprocess failure (unless "
                         "strict_c7 is on -- see strict_c7 tooltip).\n\n"
                         "humo_concat: concat-demuxer pipeline where each "
                         "HuMo clip keeps its NATIVE audio. Re-encodes audio "
                         "to AAC 192k three times (gap fill + per-clip "
                         "normalize + final concat). Pre-2026-04-30 default; "
                         "kept as fallback.\n\n"
                         "master_mix: legacy 2-layer filter graph. Audio "
                         "= procgen.wav (master_mix). HuMo clips overlay "
                         "as VIDEO only; their native audio is discarded. "
                         "Use only for comparison or if both new modes fail."
                     )},
                ),
                "strict_c7": ("BOOLEAN", {
                    "default": True,
                    "tooltip": (
                        "C7 strict mode (2026-04-30 round-robin "
                        "hardening). When ON (DEFAULT), the audio_source "
                        "fallback chain is DISABLED for paths that re-encode "
                        "audio: if master_mix_per_clip_mux fails, the node "
                        "RAISES instead of silently dropping to humo_concat "
                        "(which would 3x AAC re-encode and break C7 "
                        "byte-identity).  Lossless tier failures are still "
                        "loudly reported via ledger.meta.audio_path_selected "
                        "+ audio_path_reason.\n\n"
                        "Turn OFF only for ad-hoc debug runs where you'd "
                        "rather have ANY mp4 land than an exception.  "
                        "Production runs should leave this ON."
                    ),
                }),
            },
        }

    @staticmethod
    def _end_of_run_cleanup():
        """End-of-run VRAM release (BUG-LOCAL-123 fix 2026-04-30).

        VideoComposite is the LAST node in every OTR run. ComfyUI's
        ``model_management`` deliberately keeps loaded models resident
        across prompts to amortize load time, but for OTR that means
        HuMo (16.5 GB) + WanTE + WanVAE + Whisper stay parked in VRAM
        between consecutive runs. The next run then OOMs when Mistral-
        Nemo's _prefill tries to allocate KV cache.

        This helper fires unconditionally in execute()'s finally block
        so the next prompt starts with a clean VRAM slate, regardless
        of whether the current run succeeded, failed, or raised.

        Idempotent and bounded: never raises, always logs.
        """
        log.info("[VideoComposite] end-of-run cleanup: unloading all models")
        try:
            import comfy.model_management as mm  # type: ignore
            mm.unload_all_models()
            log.info("[VideoComposite] end-of-run: unload_all_models() OK")
        except Exception as exc:  # noqa: BLE001
            log.warning(
                "[VideoComposite] end-of-run unload_all_models() failed: %s",
                exc,
            )
        try:
            import comfy.model_management as mm  # type: ignore
            mm.soft_empty_cache(force=True)
            log.info(
                "[VideoComposite] end-of-run: soft_empty_cache(force=True) OK"
            )
        except Exception as exc_mm:  # noqa: BLE001
            log.warning(
                "[VideoComposite] end-of-run soft_empty_cache failed: %s; "
                "trying torch fallback",
                exc_mm,
            )
            try:
                import gc
                import torch  # type: ignore
                gc.collect()
                if torch.cuda.is_available():
                    torch.cuda.synchronize()
                    torch.cuda.empty_cache()
                log.info(
                    "[VideoComposite] end-of-run: torch fallback cleanup OK"
                )
            except Exception as exc:  # noqa: BLE001
                log.warning(
                    "[VideoComposite] end-of-run torch fallback failed: %s",
                    exc,
                )

    def execute(self, **kwargs):
        """Thin wrapper around ``_execute_body`` that guarantees
        end-of-run VRAM cleanup via a finally block.  See
        ``_end_of_run_cleanup`` for rationale (BUG-LOCAL-123)."""
        try:
            return self._execute_body(**kwargs)
        finally:
            self._end_of_run_cleanup()

    def _execute_body(
        self,
        procgen_video_path: str,
        clips_dir: str,
        ledger_json: str,
        blend_mode: str = "lighten",
        blend_opacity: float = 0.0,
        canvas_width: int = 1920,
        canvas_height: int = 1080,
        canvas_fps: int = 25,
        humo_target_height: int = 1080,
        fallback_clip_length: float = 7.0,
        ffmpeg: str = "ffmpeg",
        cleanup_clips_after_assembly: bool = False,
        audio_source: str = "master_mix_per_clip_mux",
        strict_c7: bool = True,
    ):
        # `cleanup_clips_after_assembly` widget is wired but the deletion
        # logic itself is deferred (would happen post-assembly when the
        # final mp4 is verified). Until then we just accept the kwarg
        # without crashing and log if it was requested -- ComfyUI passes
        # every INPUT_TYPES key as a kwarg, so the parameter MUST be in
        # the signature even if the side-effect isn't implemented yet.
        if cleanup_clips_after_assembly:
            log.info(
                "[VideoComposite] cleanup_clips_after_assembly=True requested "
                "but deletion logic is not yet implemented -- clips kept "
                "for now (this is a known TODO, not a regression)."
            )
        t_start = time.time()
        ffprobe = ffmpeg.replace("ffmpeg", "ffprobe") if ffmpeg.endswith("ffmpeg") else "ffprobe"

        # ---- Validate inputs ----
        procgen = Path(procgen_video_path.strip())
        if not procgen.exists():
            return ("", f"error: procgen_video_path not found: {procgen}")
        clips = Path(clips_dir.strip())
        if not clips.exists():
            return ("", f"error: clips_dir not found: {clips}")
        if not (shutil.which(ffmpeg) or Path(ffmpeg).exists()):
            return ("", f"error: ffmpeg not found at {ffmpeg!r}")

        ledger, ledger_path = _load_ledger_with_path(ledger_json)
        episode_id = ledger.get("episode_id", "episode")

        # ---- Resolve output_dir (intermediate composite, per-episode) ----
        # output_dir = ComfyUI/output/otr/episodes/<episode_id>/composited/
        # This is the INTERMEDIATE 832x480 composite. The downstream
        # OTR_RTXUpscale stage reads this and writes the final mp4 to
        # the OBS-watched dir at output/otr/obs/<episode_id>.mp4
        # (see otr_obs_dir). Per-episode workspace puts every working
        # file for THIS episode under one parent (audio, stills,
        # portraits, videos, composited) for tidy organization.
        out_dir = episodes_for_obs_dir(episode_id)
        out_dir.mkdir(parents=True, exist_ok=True)
        out_mp4 = out_dir / f"{episode_id}.mp4"

        # ---- Branch on audio_source ----
        # master_mix_per_clip_mux: 2026-04-30 C7 byte-perfect mode.
        # Pillarbox + concat HuMo clips silent, then mux master mix
        # audio onto the combined video with -c copy.  Falls through
        # to humo_concat if the pillarbox/concat/mux pipeline fails
        # AND strict_c7 is OFF.  When strict_c7 is ON (the default),
        # the failure raises so a silent C7-violating fallback
        # cannot ship.
        # 2026-04-30 round-robin hardening: every outcome stamps
        # ledger.meta.audio_path_selected + audio_path_reason so a
        # post-mortem can tell at a glance which tier produced the
        # final mp4 and why.
        def _stamp_audio_path(selected, reason):
            """Loud ledger signal.  Survives a failed save_ledger_safe
            (warns, doesn't raise)."""
            if ledger_path is None:
                return
            try:
                meta = ledger.setdefault("meta", {})
                meta["audio_path_selected"] = selected
                meta["audio_path_reason"] = reason
                meta["audio_source"] = selected  # back-compat alias
                from . import _otr_ledger as _OTRL  # type: ignore
                _OTRL.save_ledger_safe(ledger_path, ledger)
            except Exception as stamp_exc:  # noqa: BLE001
                log.warning(
                    "[VideoComposite] audio_path_selected=%s stamp "
                    "failed: %s", selected, stamp_exc,
                )

        if audio_source == "master_mix_per_clip_mux":
            log.info(
                "[VideoComposite] audio_source=master_mix_per_clip_mux -- "
                "C7 byte-perfect path (pillarbox + concat + mux, "
                "0 audio re-encodes downstream of SignalLostVideo); "
                "strict_c7=%s", strict_c7,
            )
            try:
                final_mp4, mux_report = _render_master_mix_per_clip_mux_mode(
                    ledger=ledger,
                    clips_dir=clips,
                    procgen=procgen,
                    out_mp4=out_mp4,
                    canvas_w=canvas_width,
                    canvas_h=canvas_height,
                    canvas_fps=canvas_fps,
                    humo_target_h=humo_target_height,
                    fallback_clip_length=fallback_clip_length,
                    ffmpeg=ffmpeg,
                    ffprobe=ffprobe,
                )
            except Exception as exc:
                # LOUD failure signal: log.exception + report-line
                # WARNING prefix.  Then either raise (strict mode) or
                # fall through to humo_concat (will re-encode audio).
                log.exception(
                    "[VideoComposite] master_mix_per_clip_mux FAILED: %s",
                    exc,
                )
                if strict_c7:
                    _stamp_audio_path(
                        "FAILED:master_mix_per_clip_mux",
                        f"strict_c7=True; not falling back to a re-encoding "
                        f"tier; reason={exc!r}",
                    )
                    raise RuntimeError(
                        "VideoComposite: strict_c7=True and "
                        "master_mix_per_clip_mux failed.  Refusing to "
                        "fall back to humo_concat (which 3x AAC re-encodes "
                        "audio and breaks C7).  Set strict_c7=False to "
                        f"allow the legacy fallback chain.  Reason: {exc}"
                    ) from exc
                # strict_c7 OFF: stamp the loud signal, fall through.
                _stamp_audio_path(
                    "humo_concat (FALLBACK from master_mix_per_clip_mux)",
                    f"per_clip_mux raised {exc!r}; strict_c7=False so "
                    f"falling back to humo_concat (audio will re-encode "
                    f"3x to AAC; C7 byte-identity NOT preserved)",
                )
            else:
                # Success path.  Stamp loud + return.
                _stamp_audio_path(
                    "master_mix_per_clip_mux",
                    "ok (zero audio re-encodes downstream of SignalLostVideo)",
                )
                if ledger_path is not None:
                    try:
                        ledger["final_video_path"] = str(final_mp4)
                        from . import _otr_ledger as _OTRL  # type: ignore
                        _OTRL.save_ledger_safe(ledger_path, ledger)
                    except Exception as stamp_exc:  # noqa: BLE001
                        log.warning(
                            "[VideoComposite] per_clip_mux final_video "
                            "stamp failed: %s", stamp_exc,
                        )
                report_lines = [
                    f"VideoComposite (master_mix_per_clip_mux mode, "
                    f"strict_c7={strict_c7})",
                    f"  episode_id: {episode_id}",
                    f"  out_mp4:    {final_mp4}",
                    "",
                    *mux_report,
                ]
                elapsed = time.time() - t_start
                log.info(
                    "[VideoComposite] per_clip_mux complete in %.1fs: %s",
                    elapsed, final_mp4,
                )
                return (str(final_mp4), "\n".join(report_lines))

        # humo_concat mode: bypass the existing 2-layer filter graph
        # entirely. Build a concat-demuxer pipeline where each HuMo
        # clip keeps its NATIVE audio (mechanical lip-sync) and gap
        # windows are filled with the radio bookend image + master_mix
        # audio slices (talking-radio identity continuous).
        if audio_source == "humo_concat" or audio_source == "master_mix_per_clip_mux":
            log.info(
                "[VideoComposite] audio_source=humo_concat -- routing to "
                "concat-demuxer pipeline (perfect lip-sync, bookend gaps)"
            )
            try:
                final_mp4, concat_report = _render_humo_concat_mode(
                    ledger=ledger,
                    clips_dir=clips,
                    procgen=procgen,
                    out_mp4=out_mp4,
                    canvas_w=canvas_width,
                    canvas_h=canvas_height,
                    canvas_fps=canvas_fps,
                    humo_target_h=humo_target_height,
                    fallback_clip_length=fallback_clip_length,
                    ffmpeg=ffmpeg,
                    ffprobe=ffprobe,
                )
            except Exception as exc:
                # BUG-LOCAL-126 fix (2026-05-01, second-Opus review):
                # Mirror the strict_c7 wrap that already exists at the
                # master_mix_per_clip_mux -> humo_concat edge.  Without
                # this, a humo_concat failure silently falls through to
                # the legacy master_mix path at line ~1194 below, which
                # uses `-c:a aac -b:a 192k` -- a real C7 violation.
                log.exception(
                    "[VideoComposite] humo_concat failed: %s", exc,
                )
                if strict_c7:
                    _stamp_audio_path(
                        "FAILED:humo_concat",
                        f"strict_c7=True; refusing master_mix legacy "
                        f"fallback (re-encodes audio AAC@192k); "
                        f"reason={exc!r}",
                    )
                    raise RuntimeError(
                        "VideoComposite: strict_c7=True and humo_concat "
                        "failed.  Refusing to fall back to master_mix "
                        "legacy mode (which AAC-re-encodes audio at "
                        "192k and breaks C7).  Set strict_c7=False to "
                        f"allow the legacy fallback chain.  Reason: {exc}"
                    ) from exc
                # strict_c7 OFF: stamp the loud signal, fall through.
                _stamp_audio_path(
                    "master_mix (FALLBACK from humo_concat)",
                    f"humo_concat raised {exc!r}; strict_c7=False so "
                    f"falling back to legacy master_mix (audio WILL "
                    f"re-encode to AAC@192k; C7 byte-identity NOT "
                    f"preserved)",
                )
                # Fall through to master_mix path on any failure.
            else:
                # Stamp final_video_path in ledger same as master_mix path.
                if ledger_path is not None:
                    try:
                        ledger["final_video_path"] = str(final_mp4)
                        with open(ledger_path, "w", encoding="utf-8") as _f:
                            json.dump(ledger, _f, indent=2)
                    except Exception as _stamp_exc:  # noqa: BLE001
                        log.warning(
                            "[VideoComposite] humo_concat ledger stamp failed: %s",
                            _stamp_exc,
                        )
                report_text = (
                    "VideoComposite (humo_concat mode)\n"
                    + "\n".join(f"  {ln}" for ln in concat_report)
                )
                return (str(final_mp4), report_text)

        # ---- Defense-in-depth: legacy master_mix re-encodes audio ----
        # BUG-LOCAL-126 (2026-05-01, second-Opus review): this block
        # uses `-c:a aac -b:a 192k` further down (line ~1225).  If
        # anyone reaches this path with strict_c7=True (current default
        # is True), the run MUST fail loudly -- regardless of which
        # upstream branch fell through.  Catches future fallthrough
        # bugs that don't honor strict_c7 at their own except clauses.
        if strict_c7:
            _stamp_audio_path(
                "FAILED:legacy_master_mix_blocked",
                "strict_c7=True; legacy master_mix uses -c:a aac -b:a "
                "192k which violates C7 byte-identity. Refusing to "
                "execute it. Set strict_c7=False if you accept the "
                "C7 violation.",
            )
            raise RuntimeError(
                "VideoComposite: strict_c7=True and execution reached "
                "the legacy master_mix path. This path AAC-re-encodes "
                "audio at 192k and breaks C7 byte-identity. If you "
                "see this raise, an upstream branch fell through "
                "without honoring strict_c7. Either fix that branch "
                "or set strict_c7=False at the workflow level."
            )

        # ---- Build clip timeline (master_mix mode) ----
        timeline = _build_clip_timeline(ledger, clips, fallback_clip_length, ffprobe)
        if not timeline:
            return ("", f"error: no HuMo clips found in {clips}")
        episode_dur = _ffprobe_dur(procgen, ffprobe) or sum(d for _, _, d in timeline)

        # ---- Build filter graph ----
        filter_graph, inputs_list = _build_filter_graph(
            procgen_video=procgen,
            timeline=timeline,
            canvas_w=canvas_width,
            canvas_h=canvas_height,
            canvas_fps=canvas_fps,
            humo_h=humo_target_height,
            blend_mode=blend_mode,
            blend_opacity=blend_opacity,
            episode_dur=episode_dur,
        )

        # ---- Build ffmpeg command ----
        cmd: list[str] = [ffmpeg, "-y", "-loglevel", "warning"]
        for inp in inputs_list:
            cmd.extend(["-i", str(inp)])
        cmd.extend([
            "-filter_complex", filter_graph,
            "-map", "[v]",
            "-map", "0:a",
            "-c:v", "libx264",
            "-preset", "medium",
            "-crf", "18",
            "-pix_fmt", "yuv420p",
            "-c:a", "aac",
            "-b:a", "192k",
            str(out_mp4),
        ])
        log.info("[VideoComposite] ffmpeg: %s", " ".join(cmd[:6] + ["..."] + [cmd[-1]]))
        log.debug("[VideoComposite] full cmd: %s", cmd)

        report = [
            f"VideoComposite: episode={episode_id}",
            f"  procgen={procgen.name}",
            f"  clips_dir={clips}",
            f"  timeline: {len(timeline)} clip(s), episode_dur={episode_dur:.2f}s",
            f"  blend_mode={blend_mode} opacity={blend_opacity}",
            f"  canvas={canvas_width}x{canvas_height}@{canvas_fps}fps",
        ]
        for clip_path, s, d in timeline[:8]:
            report.append(f"    {clip_path.name}: t={s:.2f}-{(s+d):.2f}s")
        if len(timeline) > 8:
            report.append(f"    ... +{len(timeline) - 8} more")

        # ---- Run ffmpeg ----
        try:
            r = subprocess.run(
                cmd, capture_output=True, text=True, check=False, timeout=900,
            )
            if r.returncode != 0:
                report.append(f"  FFMPEG FAIL rc={r.returncode}")
                report.append(f"  stderr: {r.stderr[-800:]}")
                return (str(out_mp4), "\n".join(report))
        except subprocess.TimeoutExpired:
            return (str(out_mp4), "error: ffmpeg timeout (>900s)")
        except Exception as exc:
            return (str(out_mp4), f"error: ffmpeg launch failed: {exc}")

        total_ms = int((time.time() - t_start) * 1000)
        report.append(f"  ffmpeg complete in {total_ms} ms")
        report.append(f"  out: {out_mp4}")

        # ---- BUG-LOCAL-089: write final_video_path back to ledger ----
        # The broadcast-tree mp4 is the canonical "this episode is
        # done" artifact. Persist its path in the ledger so OBS
        # schedulers, post-mortem tools, and any downstream re-runs
        # can resolve it via ledger lookup. Skipped silently when the
        # ledger came from inline JSON (no on-disk source).
        if ledger_path is not None:
            try:
                ledger["final_video_path"] = str(out_mp4)
                ledger["total_episode_dur_s"] = (
                    float(episode_dur) if episode_dur else
                    ledger.get("total_episode_dur_s")
                )
                with open(ledger_path, "w", encoding="utf-8") as f:
                    json.dump(ledger, f, indent=2, ensure_ascii=False)
                log.info(
                    "[VideoComposite] ledger updated: final_video_path -> %s",
                    out_mp4.name,
                )
                report.append(
                    f"  ledger updated: final_video_path={out_mp4.name}"
                )
            except Exception as exc:
                log.warning(
                    "[VideoComposite] ledger final_video_path write-back failed: %s",
                    exc,
                )
                report.append(f"  ledger write-back FAILED: {exc}")
        else:
            log.info(
                "[VideoComposite] inline ledger (no path) -- "
                "skipping final_video_path write-back"
            )
        return (str(out_mp4), "\n".join(report))


__all__ = ["VideoComposite"]
