#!/usr/bin/env python
"""Generate `docs/DEPENDENCIES.md` -- everything OTR needs, in install order.

    python scripts/otr_dependency_doc.py

WHY IT IS GENERATED. The Python package list comes from requirements.txt, so it
cannot drift from what pip actually installs. Only the parts pip CANNOT express
-- system libraries, isolated venvs, and model weights -- are declared here, and
each says why it is not just a pip line.

WHAT THIS DOCUMENT IS FOR. A person on a machine that has never run OTR. The
authoring box cannot answer that question about itself: it accreted `accelerate`
transitively from ComfyUI core, `pycairo` from another pack, `feedparser` from
something forgotten. None were installed deliberately, and requirements.txt was
never what made them present. A rented pod found all three in one day precisely
because it inherits nothing.
"""
from __future__ import annotations

import io
import os
import re
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.dirname(_HERE)

#: Things pip cannot install, with the symptom you get without them.
SYSTEM_LIBS = [
    ("libcairo2-dev, pkg-config", "apt-get install -y libcairo2-dev pkg-config",
     "pycairo is a C extension. Without these, `pip install pycairo` fails at "
     "metadata generation -- and because `import cairo` sits UNGUARDED inside "
     "the draw function, every viz_mandala frame and every scope overlay then "
     "raises ImportError at RENDER time, not at install."),
    ("ffmpeg", "apt-get install -y ffmpeg  (or ships with the image)",
     "muxing, captions and the credits concat. Note: having ffmpeg proves "
     "nothing about NVENC -- most containers expose CUDA for compute but not "
     "libnvidia-encode.so.1, and OTR falls back to CPU encoding automatically."),
]

#: Engines that run in their OWN venv, on purpose.
ISOLATED = [
    ("indextts2", "index-tts", "https://github.com/index-tts/index-tts.git",
     "pins >=3.10,<3.12 -- build the venv with `uv venv --python 3.11`",
     "OTR_INDEXTTS2_VENV / _DIR / _WORKER",
     "the default character voice. Non-commercial licence, so it is NOT "
     "offered for the announcer. Needs reference WAVs (below)."),
    ("chatterbox", "chatterbox", "pip: chatterbox-tts soundfile torch torchaudio",
     "own venv; torch pinned separately from ComfyUI's",
     "OTR_CHATTERBOX_VENV / _WORKER",
     "MIT, commercial-clean, and announcer-capable -- one of only two cloning "
     "engines the announcer accepts."),
    ("dia", "dia", "pip: git+https://github.com/nari-labs/dia.git",
     "own venv; torch pinned separately",
     "OTR_DIA_VENV / _WORKER",
     "Apache, the second commercial-clean cloner, also announcer-capable."),
]

_WHY_ISOLATED = (
    "Each pins torch/transformers versions that would brick ComfyUI's own venv, "
    "so they run as supervised subprocess workers over line-delimited JSON with "
    "ZERO shared torch.")


def requirements() -> list:
    out = []
    path = os.path.join(_REPO, "requirements.txt")
    for line in io.open(path, encoding="utf-8"):
        raw = line.split("#")[0].strip()
        if raw:
            out.append(raw)
    return out


def render() -> str:
    L, A = [], None
    A = L.append
    A("# Everything OTR needs, and how to install it\n")
    A("**GENERATED by `scripts/otr_dependency_doc.py`. Do not hand-edit.**\n")
    A("Written for a machine that has never run OTR. If you are on the box "
      "that developed it, this list will look longer than your experience "
      "suggests -- that is the point. A developer machine accretes packages "
      "invisibly: `accelerate` arrived transitively from ComfyUI core, "
      "`pycairo` from another node pack, `feedparser` from something long "
      "forgotten. None were installed deliberately, and a fresh machine "
      "inherits none of them.\n")

    A("## The short version\n")
    A("```bash\n"
      "# 1. system libraries pip cannot provide (Linux)\n"
      "sudo apt-get install -y libcairo2-dev pkg-config ffmpeg\n\n"
      "# 2. the pack and its Python dependencies -- INTO THE PYTHON COMFYUI RUNS\n"
      "git clone -b v2.0-alpha https://github.com/jbrick2070/ComfyUI-OldTimeRadio\n"
      "<comfyui-python> -m pip install -r ComfyUI-OldTimeRadio/requirements.txt\n\n"
      "# 3. model weights for the lane you want\n"
      "python scripts/otr_fetch_lane_weights.py haunted\n\n"
      "# 4. check what actually landed\n"
      "python scripts/otr_venv_audit.py\n"
      "```\n")
    A("**Step 2 is where installs go wrong.** ComfyUI usually runs its own "
      "venv, and `python3 -m pip` installs somewhere else. That single mistake "
      "produced three separate failures in one day -- a writer that died at 18 "
      "seconds, an RSS fetch that blamed the feeds, and a quantiser that "
      "reported a missing library it had been given. Find the right "
      "interpreter:\n")
    A("```bash\n"
      "python3 -c \"import folder_paths,os;print(os.path.dirname(folder_paths.__file__))\"\n"
      "# then use that tree's venv python, e.g. <root>/.venv/bin/python\n"
      "```\n")

    A("## 0. ComfyUI itself has a minimum version\n")
    A("Some lanes resolve node classes that live in ComfyUI CORE, not in any "
      "node pack, so an older ComfyUI fails them no matter what you install. "
      "The failure arrives at RENDER time as WrapperNodeMissing, typically "
      "seventeen minutes in, after the script, cast, voices and stills are "
      "already done -- it looks nothing like a version problem.\n")
    A("| lane | needs | why |")
    A("|---|---|---|")
    A("| `ltx25` (video / foley_plus / mime) | **ComfyUI >= v0.32.0** | "
      "`LTXVDualCFGGuider` and `LTXVModalityGuidance` entered core in "
      "commit 57ce8e1a, `Add support for LTX 2.5 (#15499)`, 2026-08-11. "
      "First tag containing them is v0.32.0. |")
    A("\nCheck yours with `git describe --tags` in the ComfyUI directory. A "
      "rented pod image measured v0.26.2 (2026-06-30) -- two months and "
      "eight minor versions behind -- and the ltx25 lane was unrunnable there "
      "for that reason alone, with every weight and node pack correctly "
      "installed.\n")
    A("## 1. System libraries -- pip cannot install these\n")
    A("| package | install | why, and what breaks without it |")
    A("|---|---|---|")
    for name, cmd, why in SYSTEM_LIBS:
        A("| `%s` | `%s` | %s |" % (name, cmd, why))
    A("")

    A("## 2. Python packages\n")
    A("From `requirements.txt`, which is the authority -- this list is read "
      "from it:\n")
    A("```")
    for line in requirements():
        A(line)
    A("```\n")

    A("## 3. Isolated-venv voice engines\n")
    A("%s\n" % _WHY_ISOLATED)
    A("**Do NOT edit their adapters to make paths work on your OS.** Qualified "
      "voice routes are pinned to an adapter fingerprint, so any edit "
      "un-qualifies every route audited against it and the cast silently falls "
      "back to an ordinary draw -- the episode still renders, which is what "
      "makes it easy to miss. Use the environment variables instead.\n")
    for name, dirname, source, build, envs, why in ISOLATED:
        A("### `%s`\n" % name)
        A("* install to: `<comfy-root>/%s` (or anywhere, and set the env var)" % dirname)
        A("* source: `%s`" % source)
        A("* build: %s" % build)
        A("* env: `%s`" % envs)
        A("* %s\n" % why)
    A("**Reference WAVs** for cloning engines live at "
      "`<models_root>/TTS/refs/<engine>/*.wav`, one per cast voice. They ship "
      "with nothing. Without a resolvable reference the engine refuses by name "
      "and there is no fallback.\n")

    A("## 3b. Other custom node packs\n")
    A("OTR resolves these node CLASSES by name at render time, so a missing "
      "pack does not fail at startup -- it fails deep inside an episode, "
      "after the script, cast, voices and stills are already done. wan_ti2v "
      "died seventeen minutes in with WrapperNodeMissing for exactly this "
      "reason.\n")
    A("| pack | who needs it | what breaks without it |")
    A("|---|---|---|")
    A("| [ComfyUI-AnimateDiff-Evolved](https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved) | the animatediff lane | that lane only |")
    A("| [ComfyUI-GGUF](https://github.com/city96/ComfyUI-GGUF) | "
      "`wan_ti2v`, `ltx25` | `UnetLoaderGGUF` / `CLIPLoaderGGUF`. Both "
      "lanes default to GGUF weights, so both are dead without it. |")
    A("| [ComfyUI-LTXVideo](https://github.com/Lightricks/ComfyUI-LTXVideo) "
      "| `ltx25` | the advanced LTXV nodes (ImgToVideoInplace, "
      "LatentUpsampler, DualCFGGuider, Concat/SeparateAVLatent, "
      "AudioVAEDecode, EmptyLatentAudio, ModalityGuidance). ComfyUI core "
      "ships only Conditioning/Scheduler/ImgToVideo -- enough for "
      "`ltx_8gb`, not for `ltx25`. |")
    A("\n`scripts/otr_provision.py` clones all three. If you install by hand, "
      "clone into `<comfy>/custom_nodes/` and restart ComfyUI -- node "
      "classes are registered at startup.\n")
    A("## 4. Model weights\n")
    A("See [MODEL_ASSET_INDEX.md](MODEL_ASSET_INDEX.md) -- generated from the "
      "engine code, and the only place file names, repo ids and sizes are "
      "recorded. `scripts/otr_fetch_lane_weights.py --list` shows which lanes "
      "install with one command.\n")
    A("### The image model depends on your GPU\n")
    A("`z_image_turbo` is the image engine every machine class uses, and "
      "it ships in three precisions. The adapter ranks whatever is "
      "installed nvfp4 > fp8 > bf16 and takes the best -- which is a trap "
      "if you install the wrong one, because nvfp4 needs hardware fp4 "
      "(Blackwell, sm_120) and an older card cannot execute it. The "
      "ranking still chooses it, so the engine picks the one file that "
      "fails.\n")
    A("```bash\n"
      "python scripts/otr_fetch_lane_weights.py z_image            # bf16, any NVIDIA\n"
      "python scripts/otr_fetch_lane_weights.py z_image_blackwell  # nvfp4, sm_120 only\n"
      "```\n")
    A("Fetch ONE, not both. `scripts/otr_pod_provision.sh` reads "
      "compute_cap and picks for you. If a shared volume already carries "
      "nvfp4 and your card cannot run it, move that file OUT of the models "
      "tree -- a subfolder does not hide it, because the ranking matches "
      "on basename.\n")
    A("Two environment variables decide where everything lands:\n")
    A("```\n"
      "OTR_COMFYUI_MODELS_ROOT   the models root\n"
      "HF_HOME                   MUST be <models_root>/huggingface\n"
      "```\n")
    A("Setting `HF_HOME` anywhere else does not relocate the cache, it ADDS "
      "one. That mistake cost 84 GB of duplicate weights and surfaced only as "
      "a disk-quota error on a half-empty volume.\n")

    A("## 5. Verify\n")
    A("```bash\n"
      "python scripts/otr_venv_audit.py     # what is imported vs declared vs installed\n"
      "curl -s $URL/object_info | grep -c OTR_   # non-zero means the pack loaded\n"
      "```\n")
    A("`otr_venv_audit.py` reports and never gates. Two things it cannot see, "
      "stated so you do not over-trust it: a declared wheel that needs a system "
      "library underneath it, and packages your DEPENDENCIES import at runtime "
      "-- `bitsandbytes` never appears in OTR's source because transformers "
      "imports it, not us.\n")
    return "\n".join(L) + "\n"


def main() -> int:
    text = render()
    dest = os.path.join(_REPO, "docs", "DEPENDENCIES.md")
    io.open(dest, "w", encoding="utf-8", newline="\n").write(text)
    print("wrote %s (%d bytes)" % (dest, len(text)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
