"""Regenerate the Shakespeare gap matrix from leads.json, against the CANONICAL
14 target scenes.

Classifying against the real target list is the point: a lead recorded at a
coordinate nobody asked for looks like progress on a tally and delivers
nothing, which is exactly what this caught on the first run.

IN THE TREE ON PURPOSE. This lived in a scratchpad for its first few runs,
which meant the tally the operator was reading could not be regenerated by
anyone else -- including the next session -- from the repo alone, while the
document it wrote said "Generated from leads.json" as though it could. Found
by the Fable architecture review, 2026-09-18.

Run it after any edit to leads.json:
    python scripts/otr_shakespeare_gap_matrix.py
"""
import io
import json
import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LEADS = os.path.join(REPO, "config", "source_banks", "shakespeare",
                     "translations", "leads.json")
OUT = os.path.join(REPO, "docs", "2026-09-18-fidelity-lane-translation",
                   "GAP_MATRIX.md")

# The 14 target scenes, exactly as the matrix has always named them.
TARGETS = [
    ("macbeth", "1.3"), ("tempest", "1.2"), ("tempest", "3.1"),
    ("midsummer", "3.1"), ("midsummer", "3.2"),
    ("twelfth_night", "1.5"), ("twelfth_night", "2.5"),
    ("much_ado", "2.3"), ("much_ado", "3.1"),
    ("as_you_like_it", "3.2"), ("hamlet", "1.1"), ("king_lear", "1.1"),
    ("romeo_juliet", "2.2"), ("comedy_errors", "3.1"),
]
LANGS = [("fr", "French"), ("it", "Italian"), ("es", "Spanish"),
         ("pt", "Portuguese"), ("ja", "Japanese"), ("hi", "Hindi"),
         ("zh", "Mandarin")]

# Spellings seen in leads.json that mean the same target play.
ALIASES = {"comedy_of_errors": "comedy_errors"}


def play_of(row):
    return ALIASES.get(str(row.get("play") or ""), str(row.get("play") or ""))


def classify(rows):
    """Best state among the leads for one cell."""
    if not rows:
        return "NO LEAD", ""
    best, note = "BLOCKED", ""
    for row in rows:
        if row.get("excluded"):
            continue
        # No HOLD-RIGHTS state: rights decide nothing (operator 2026-09-18,
        # "I don't want to waste anything in rights"). A located source is
        # simply located, and the translator and publication years travel on
        # the row as data.
        has_url = bool(str(row.get("url") or "").strip())
        state = "HAVE-URL" if has_url else "NEED-URL"
        rank = {"HAVE-URL": 0, "NEED-URL": 1, "BLOCKED": 2}
        if rank[state] < rank.get(best, 9):
            best, note = state, str(row.get("translator") or "")
    if best == "BLOCKED" and all(r.get("excluded") for r in rows):
        return "BLOCKED", "all leads excluded"
    return best, note


def main():
    with io.open(LEADS, encoding="utf-8") as handle:
        leads = json.load(handle)["leads"]

    cells = {}
    for row in leads:
        cells.setdefault((row.get("iso"), play_of(row), row.get("scene")),
                         []).append(row)

    target_keys = {(iso, play, scene)
                   for iso, _ in LANGS for play, scene in TARGETS}
    stray = sorted(k for k in cells if k not in target_keys)

    lines = []
    lines.append("# Shakespeare translation gaps -- FINAL, 2026-09-18")
    lines.append("")
    lines.append("Generated from `config/source_banks/shakespeare/"
                 "translations/leads.json` against the canonical 14 target "
                 "scenes. 14 x 7 = 98 cells.")
    lines.append("")
    lines.append("- **HAVE-URL** -- rights-cleared lead with a page located. "
                 "Still needs the scene resolved out of it, or transcription "
                 "if it is a scan. NOTHING here is vendored yet.")
    lines.append("- **NEED-URL** -- a translator is named, no page found yet.")
    lines.append("- **BLOCKED** -- every lead for the cell is excluded, on "
                 "FIDELITY or because no transcription exists. Never on "
                 "rights, which gate nothing here.")
    lines.append("- **NO LEAD** -- nothing at all.")
    lines.append("")
    header = "| Scene | " + " | ".join(name for _, name in LANGS) + " |"
    lines.append(header)
    lines.append("|---" * (len(LANGS) + 1) + "|")

    tally = {}
    for play, scene in TARGETS:
        row_out = ["%s %s" % (play, scene)]
        for iso, _ in LANGS:
            state, _note = classify(cells.get((iso, play, scene), []))
            tally[state] = tally.get(state, 0) + 1
            row_out.append(state)
        lines.append("| " + " | ".join(row_out) + " |")

    lines.append("")
    lines.append("## Tally")
    lines.append("")
    for state in ("HAVE-URL", "NEED-URL", "BLOCKED", "NO LEAD"):
        lines.append("- %-12s %d of 98" % (state, tally.get(state, 0)))

    if stray:
        lines.append("")
        lines.append("## Leads recorded at coordinates NOBODY ASKED FOR")
        lines.append("")
        lines.append("These are real located sources, but they sit at a "
                     "(play, scene) that is not one of the 14 targets, so "
                     "they move no cell. Either the target list grows to want "
                     "them, or they are noise on the tally. Listed rather "
                     "than deleted because the URLs are good.")
        lines.append("")
        for iso, play, scene in stray:
            who = ", ".join(sorted({str(r.get("translator") or "?")
                                    for r in cells[(iso, play, scene)]}))
            lines.append("- `%s` %s %s -- %s" % (iso, play, scene, who))

    with io.open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines) + "\n")
    print("\n".join(lines[:40]))
    print("\n... wrote %s" % OUT)
    print("STRAY CELLS: %d" % len(stray))


if __name__ == "__main__":
    main()
