"""
verify_flux_coverage.py -- prove every beat in the ledger has a FLUX still.

For each beat in <ledger>:
  - dialogue beat (kind=dialogue, speaker not RADIO):
      requires both:
        portrait_<speaker>     (one PNG, any run)
        composite_<shot>_<spkr> (one PNG, any run)
  - ambient beat (kind=ambient, speaker=RADIO):
      requires:
        portrait_radio (one PNG)

The script lists every (shot_id, beat_id, speaker, kind) and prints PRESENT
or MISSING for the corresponding FLUX outputs. Exits non-zero if anything
is missing so it can be wired into a CI gate later.

Filenames generated by render_flux_batch.py follow:
  pass1: otr_humo_pass1_portrait_<slug>_NNNNN_.png
  pass3: otr_humo_pass3_<shot>_<spkr_slug>_NNNNN_.png

Usage:
    python scripts/verify_flux_coverage.py <ledger.json> [--out-dir <dir>]

Default --out-dir resolves via ``nodes._otr_paths.comfy_output_dir()``
(checks ``OTR_OUTPUT_DIR`` env var, then ComfyUI's API, then walks up
to the ComfyUI repo root).
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

# Make ``nodes._otr_paths`` importable when running this script directly.
_REPO_ROOT = Path(__file__).resolve().parents[1]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))
from nodes._otr_paths import comfy_output_dir  # noqa: E402

DEFAULT_OUT_DIR = comfy_output_dir()


def slugify(name: str) -> str:
    """Match the slug rule in render_flux_batch.slugify."""
    s = (name or "unnamed").strip().lower()
    s = re.sub(r"[^a-z0-9]+", "_", s).strip("_")
    return s or "unnamed"


def load_ledger(p: Path) -> dict:
    return json.loads(p.read_text(encoding="utf-8"))


def expected_targets(ledger: dict) -> tuple[list[dict], list[dict]]:
    """Return (portraits_expected, composites_expected) lists."""
    cast = ledger.get("cast", []) or []
    shots = ledger.get("shots", []) or []

    # Portraits: one per cast member that ever speaks, plus RADIO if present.
    portraits = []
    for c in cast:
        name = (c.get("name") or "").strip()
        if not name:
            continue
        portraits.append({"speaker": name, "slug": slugify(name)})

    # Composites: one per (shot_id, speaker) pair where speaker != RADIO and
    # the beat kind is dialogue. Same-speaker beats inside one shot share one.
    seen = set()
    composites = []
    for sh in shots:
        sid = sh.get("shot_id")
        for b in (sh.get("beats") or []):
            speaker = (b.get("speaker") or "").strip()
            kind = b.get("kind") or "dialogue"
            if not speaker or speaker.upper() == "RADIO":
                continue
            if kind != "dialogue":
                continue
            key = (sid, speaker)
            if key in seen:
                continue
            seen.add(key)
            composites.append({"shot_id": sid, "speaker": speaker,
                               "slug": slugify(speaker)})
    return portraits, composites


def find_files_for(out_dir: Path, pass_label: str, slug_pattern: str) -> list[Path]:
    """Find any PNGs matching the pass + slug pattern. ComfyUI appends NNNNN_.

    Searches three generations of paths for backwards compatibility:
      - NEW (final):   output/otr/stills/<pass>_<slug>_NNNNN_.png
      - MID (today):   output/otr_stills/<pass>_<slug>_NNNNN_.png
      - LEGACY:        output/otr_humo_<pass>_<slug>_NNNNN_.png  (root)
    """
    new_pat = f"otr/stills/{pass_label}_{slug_pattern}_*.png"
    mid_pat = f"otr_stills/{pass_label}_{slug_pattern}_*.png"
    legacy_pat = f"otr_humo_{pass_label}_{slug_pattern}_*.png"
    return sorted(
        list(out_dir.glob(new_pat))
        + list(out_dir.glob(mid_pat))
        + list(out_dir.glob(legacy_pat))
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("ledger", type=Path)
    ap.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    args = ap.parse_args()

    if not args.ledger.exists():
        print(f"FATAL: ledger not found: {args.ledger}", file=sys.stderr)
        return 2

    led = load_ledger(args.ledger)
    portraits, composites = expected_targets(led)

    print(f"[ledger] {args.ledger}")
    print(f"[out_dir] {args.out_dir}")
    print(f"[expected] portraits: {len(portraits)}   composites: {len(composites)}")
    print()

    # ---- Portraits ----
    print("PORTRAIT COVERAGE")
    print("-" * 60)
    missing_portraits = []
    for p in portraits:
        files = find_files_for(args.out_dir, "pass1", f"portrait_{p['slug']}")
        status = "PRESENT" if files else "MISSING"
        if not files:
            missing_portraits.append(p["speaker"])
        n = len(files)
        latest = files[-1].name if files else "(none)"
        print(f"  {status:8s}  {p['speaker']:14s}  {n} run(s)  latest={latest}")

    # ---- Composites ----
    print()
    print("PER-(SHOT, SPEAKER) COMPOSITE COVERAGE")
    print("-" * 60)
    missing_composites = []
    by_shot = defaultdict(list)
    for c in composites:
        by_shot[c["shot_id"]].append(c)
    for sid in sorted(by_shot.keys()):
        for c in by_shot[sid]:
            files = find_files_for(
                args.out_dir, "pass3",
                f"{sid}_{c['slug']}",
            )
            status = "PRESENT" if files else "MISSING"
            if not files:
                missing_composites.append((sid, c["speaker"]))
            n = len(files)
            latest = files[-1].name if files else "(none)"
            print(f"  {status:8s}  {sid:14s}  {c['speaker']:12s}  "
                  f"{n} run(s)  latest={latest}")

    # ---- Summary ----
    print()
    print("=" * 60)
    print(f"PORTRAITS  : {len(portraits) - len(missing_portraits)}/{len(portraits)} present")
    print(f"COMPOSITES : {len(composites) - len(missing_composites)}/{len(composites)} present")
    if missing_portraits:
        print()
        print("Missing portraits:")
        for s in missing_portraits:
            print(f"  - {s}")
    if missing_composites:
        print()
        print("Missing composites:")
        for sid, sp in missing_composites:
            print(f"  - {sid} / {sp}")

    if missing_portraits or missing_composites:
        print()
        print("[result] INCOMPLETE -- some beats have no FLUX still")
        return 1
    print()
    print("[result] COMPLETE -- every dialogue / ambient beat has its FLUX still")
    return 0


if __name__ == "__main__":
    sys.exit(main())
